[Container]
Volume=%S/grafana:/var/lib/grafana:rw,z

[Service]
ExecStartPre=/bin/sh -c 'chown -R "$(podman image inspect {{ .Grafana.Image }}:{{ .Grafana.Tag }} | jq -r .[0].Config.User)" %S/grafana || true'
