// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rc9s4suhfweGeqtgzkvxIZu6Ot6b2epzH+ExeazveqjvO7kAkJOGYBDgAKEeb4/Pbb3UDIEGRtCXZ",
	"cZIdfkksEsSj0eg3uj9GscxyKZgwOjr4GOl4xjKKfx5OJiw2LHmeMmbgAU0SbrgUNH2rZM6U4UxHBxOa",
	"ajaIEqZjxXN4Hx1EbwQjE/iOSEXMzP1ImdaETqeKTalh5IqbGUnYnMeMUJEQntEpI7EshNFkIhWh5Oj8",
	"2SgaRHkw3seIuok9xU/xUX1094JwQcyM62om1SymShY58T2R8QJn6YabSJVREx1EXJjvn0SDyCxyZn+y",
	"KVPR9SCacJFwMW0Z/C1Tw4RPmTbEN8KV3jYZGJgblmGX/6nYJDqI/rRT7c6O25qd8yIVTNExT7lZvIBP",
	"jw3LYFJumlQpusBJwgivacaas8RNJRkzNKGGjgTN2ICwLDcLhHzHlo0qWGijuJiWo0C75ihnqmDkasbc",
	"0pW8IorlimlYkNt6TYQ0RF4Juw3UjhuMNJYyZVRE19eDSLHfC65YEh38GqwunMOggR7BZr0vO5Xj/2ax",
	"gekf5vycKY0TXp7/4dtj944kbMIF0wiZuX3GEmL3hMiJW6BfHIUO4DEVxA41IqdMwYdEz2SRJiSWYs6U",
	"IYrFcir4v8reNDESh0mpASwCrFOCpmRO04IN8KhkdEEUg35JIYIesIkekVdSMcLFRB6QmTG5PtjZmXIz",
	"uvyzHnEJSJUVgpvFTiyFUXxcGKn0TsLmLN3RfDqkKp5xw2JTKLZDcz7EyQpYlB5lyZ8U07JQMdOwTUwU",
	"GezHfI+m+Yzu4Xbw6czEJoXRyufvl5FnEH0YwtfDOVWAgRq6qfbjvOqwevjcd30sz4OOPwyncthAzSNq",
	"aCqntxIv9oFmeYrHhAbo0LGOQXTJRRIdlN0PIn+QoAeBBy5iyZQNaZ5rmIjOWYzoxXWe0oU9k9GzZMrI",
	"YZ6nPEaE0YjjS8Suhp430YUAka/9FJcR+hcOdFYTSiyQLMJUeAuPAPVOnp2eEb/LFrctGgfnt8JowEYu",
	"Jkw5Cqdkhr0wkeSSC4M/4pQzYYguxhk3cFR+L5g2gOwjckQFEIExI0WeUMOSETkW5IhmLD2imn1yfAbE",
	"0UMAmW4lceH23rQF870xM3TvnzJngub8n28QZq+YoSES3NSDQ6lTaAqfGGoKvepHtvEynQwwyKFFsCA3",
	"qzbC6HpF5rIe9w++DOk9FYRWyE4My3IgcRZfKIntVyNybEiu5JwnDHjEhBapAWo54dNC2U8tmSNmRg2J",
	"qQDEiQttZIZEEBkOTNchc21QGXKYr+ao3QUpg93YABPhM4uN949Wh8rwCY3XFS4PBaHuS6LYhCkmYjYi",
	"ZzNGYDQy4SxF0AN4Ew6fZlxQAxIl8M5CW1Ij+O8Fq2QzVvaqScp1C4KIVlHqTW7nTWZFRsVQMZrQcYoj",
	"A60n8JUTqgAd3BjIOT3bif529Obv++Qp15fkGKTgtv22D1beNA/cM/jsehAVircIOB6O706OERKyMF68",
	"Ib8XNOUTzpSFrX9cgpxsGToFSdaKu9uI7XDWWEKoQZxOC3vqeMbqC/69oAsg3YolM2p21Iylw7GUJh7+",
	"HsurfcAlLl4yMTWz6GCvAY0lXMS3dokrotyZA2YHOKwGUEeeEXm1KuaQYxGnBdAvuybUbIbjgqcJU0QW",
	"Ji/8GDURCtgX5YKpaBB5ONCMg2agJfwtaCxFQof25zxLLuG/GZw9Ra+iQTSNmf92mHB9Oay6fB/CPxxp",
	"BaGsA4JHQS8dTf7mltHx+hBX1/HyGFfZ9aWDxY2Nzi2Eut4i4DpeniA8O16+QDDftGQ4yxV43tex8Iga",
	"NpVqYTEQORzobRWfilpYKn6BOoVnlQT0xRB/9EIDtx7Uunq/7g77sU59by3vDsMBlhbnWfU4bTliRzVG",
	"jqS6zsiBcQDVQRoCCyQpyHFki5bSgN5GQi7nTCmeJMDtK6qFrUfE8aah/dgJDJMiTUFxylMaM+y8/n4L",
	"pNCMqSlLtpvk38og3czKqKIpCrXJLVtMzM+p0gOSS2X0gMxlWmRMD0o5QA8IM/Fou0Y0P0buO/jz5ZsX",
	"/3z57PzZS7RLTCTQOewNNvOH3R92D+Af3JsGPbQLOUWesd5y/uv0zWtiP7QaMUgxcbDhJKeKZsyAWgB7",
	"ZGaMK1g3TxAEgSRTzQdYZhtnfcoM5SlLSCLjIvNq9YDkyILoOAW1g2RUXSbySjiC2iIrXd/ME56yPJUL",
	"6H9zObfqoybxemyOSVI1aBzhQCpFdoqGixE5rDeiWsuYg3YUtsejM6OaCFkaVLgm2vA0hZ3RPGEKDlMw",
	"A+g6mA9InCJdhAOgaa40AuFOwtGAJ1wkfM6TgqbVeILEVDMNkrdiOBQa9bgmhQYMWVpuMLY7+VmpBbhP",
	"AW6VhiDF/UvtAYnsMJFJVZu2sycy8ij49BE0QYo4wHco7KE5qK53SPupWx2u2v4Od2FpA0bkxMk41hoa",
	"dFebV6t2EFemjyWbHOji7nM30bjC47qUVtkwukfw+mHnKKgGuhVzHS45lkoxnUuRoBmgNrSYcvGhddgZ",
	"FYKlHUPalwPCJ4QK3BOKoOXCMJHYozNmxCgaXzq4BhAoGWpjVDtrlpzJ9oHdxnqzbvt6AWspF36xdTz2",
	"pP+XVm3yGTczpgglT8uBni/ZSavJ+q7a8fpsCU2Xpr4i/fxMSu+8y1Qbaih1tHYk1iGC38j2Zd6m4Mal",
	"xS/E/mpa71flNC+5vhduA/1YgIPiAStvbabvj26WPor67F7eOvxKzo12ttzi2+jtm1+AfRM23dqU1jMO",
	"WVS4/bAo5lSM9U5K8CUCFcRC1DbQp1gjC1J5qjEib3HjYyviAFtHaoE9sYRYU2zzHGVMazptobMl83Yt",
	"CPuQp9SKzFezhcUlXhsD5Kwr5BySJJJwoQ2jSZ0xnuFnMPfatyPyTjOCXHOYp4UOP25hEKgBeZG3w54V",
	"MongizoAtwItCqTI7RY2jhO6ld56QN6CFnejnDfSy89CJTeijT1F/CNSROwYkDJN30yig1/v4Iz6uGzb",
	"WEVdMCXpGbNUiqndylOe8ZQqoFloTcrRtiLIL8WYKcGM8xKvolQswcxPqgmW98tH/JUDJdL4uv/Ju6rJ",
	"sw+gA2hSAcLquX55OpY5F9NWE8WyN2RjAgRf14IJ6p6tJotqoUne2HyDAdsaZxDdK99DrVvyFCeRECli",
	"9pemdV9bA/6cEUbjWeVx4SJhOehSwqSLETlb5OwGl4p3pJTb/+tHD9zQBI3OidIpkCuZMTNjhQ7+xE1f",
	"l06WHqZrdCgc28/3msQzDiyyK/ZdGnFRPbSGyXU+D82kVsMMxZ3VheTyK+gkjC9YRo6fb/BP6Zm8EtaQ",
	"Y3EENo6LaTt1rNnj3qm0jdGJS6AI7IMLXql90trpTGYsb5WkgAb5t+TdyctWtZ3kSmKgTVvfPG7TGaEr",
	"qQjSjXcnx616I3yJ43lwcUHeHbcO4pzWqiUmzL2B0fJinHINynzbcFuw3VQsMG6O0Qx3Z7t1OD2TyjwN",
	"x2lQAzJWnE2IFGyYcgGqfvm6bfT2YYo8l8p0b7FrUFFahGm43Qi/KTMobMxYmo/uwb/p/ZqOcLURwznl",
	"KaK6b+PMkUdcxFwIajjJZMJSKzs7EdfSy1zxjKoFAWY1IPqS59rGFWiDPTpDk3uDIVoZSzg11WDLZM99",
	"ggZ620s0iCZUG+BvFdl1ngZHGg8iPaP7331/QB+z5IfvYsrGu/uTCfv+z3GS/DBJ/vzkye733/95l7If",
	"HiffP34cj/e+f7K/n+zusj/T/xPv7//w3XfjJ98nTwKxX0cH0f7oyZPRbjSIcAEwpf3Rk8ejXZhLaWOB",
	"Z9+NdlFcCGd/+6Tnrv/GoI9x0NoI2G4D2h5I23Vq3u4crrhmgDO3CFztXmJkeXJSP7iO54Gg63lJ6JmT",
	"Ng5RZVdUwWwSxefI+UIuOGNpFg2ADSYpM/gyy6XG9iAmru3Jg5m+OY0aa3peTWTpzVM/r6XnHZ5eePWz",
	"nfXS07+Vi2j05Ne0PDQusb4Bge61mtDbzWAbEm+J0A0XpXtjhSYvGAUib6iwNTWHm8SM+2HyaLB9zigo",
	"N7pbFP3YZsZuxkmTie2JuEODBjtrLy3dMSjgaWq4niycCZ2lfMqBFHrx8kKUlpRf2EITqkrbsh8BcRSt",
	"HM4TCm2secE7OlxLfD+6EMD6r1iaDi8FuvhqHcGWXGEfsRTaKIryLLAk73Wzw/yFVAC6EBYaQ3xVDmhV",
	"2jFDboYRLLCsiVRXVCUEmbLhNuR6dCHqXtlpXoycihwdREYVgNxSj4C3RAcRBn9EjcDO2lfLKPj3GXP2",
	"/hdv34H67loi7GjJ12pepZDcuEmgMtIkG9eD6HKejZiATpLu0X85f0UuQYdLgU8WqduwVNLEGatA4965",
	"nGfBFNeaRgmlhhHqlGRU0Km1OEGbAxtL424JwBOydWGBexFto7ykqN9lktP4Mmznfl9E2+H8uIu1cm9b",
	"pthwfdRDjTOa/2qbvg+tayFb7DqbN8Y3NdRbmqPb2CthGOdmpANGLQzLnT48sRk1oLrZ5lzguRiVjHBE",
	"3oh0QS7ZAnazjGCCLa5QrFQe/eGu4/6nkFR87JMVI6wAAuAK4bd3+750ROe8b5hB9ers5RRZUov9AegU",
	"yJaVsOlsaKISLAdVyAScWi9iFvlU0YShqDlCifuS5ydUWE1onXnZj5qTO2XZnCmi4DWgUSkOl3E3fg4J",
	"Vyw26cJeQbDzt9Ix4MG/htooUEqszQ4F/Zk0E/5h2cZzUezuPmY/7o12R7sEf8R7o8d2J53E2ZDWy3Oy",
	"0fxWFM5BdB1itEO7mB7hlKNBtDfas9LwSmKpx4smx5+vK8F0otgpy6gwwNQcgvGECYMBmmSLjaajAdkb",
	"7Y8eD8g+rGGo4r3tpRCC0kGqEobGYKDhHrZTRfNZfRv98VuSqOelIbMUompUbwV73WHorF3yyUxkmsor",
	"f0yWlTUXZOK370IAvRIysXEoAa7genCFfpaWe9Ex/IkHVGr36ehCvAuOoRderIFsvKh0wy17yLe9TriV",
	"FanhOT6R6kKUZ5ds6eDUbQchoR0iahgLdyFcbFstSM0bmawA0qW3bO4f6fSNPLhfZG2fSO8P+aP5Qza3",
	"wjsLPLwZt9rgQ4o0KlHS6xlW3LFWolTGNE0XQyuqJrf4Eh/IOLuZrfPBzJyfy8L5OY2bNwSgnpY3vDbA",
	"ZPw2DDjF9RZKIZ2xb2v81S6iNbTZDt5mDgn6Y8u7WXW4ErleJg9HftxbrXjBDFupwpwd4cXxnxanbM4U",
	"N4t1YWrvncsJHAHDRWzI0fmzMuhTqikV/F92y8cLMuPTGdOGaDdaC0wVNzymaVsMfGHDgKuRXFsccsUr",
	"6DCDVfr+mU9n6/SbyqtVun0pr9bpFQTwIlul41fYcp2+hRRsJSjDfqLLV0iMxpHcKgw8y0Gr3jo6Pz0l",
	"OgZWu7u94uBGmrY9PoPHS0PTWEmtG+i04kCFQBvYegt1HwHVKgSuLKmh7K3jLhvTcbWDCrkdHpYbbPHH",
	"7Uk16bYza82P939sfVh6md2h5QgPbNIFK93Pw4wKG53o10U2tqzOD36FysUylfApIUAC9b3d6bhvMjC8",
	"uwst2GTMVF7dkVBsMqrt605UZJNhoae7UY9g1GWsxmNNDUkZBZ1JsCX0Lech7p3QbAIL19mXQWtqqVNO",
	"iyyjanGCNxA0W5PueHJFtO3GRe44G2Blkb8ntTlrDYzAu8LBhVzUO/0NGhuvSg7H6DhwWVhKl4y7MqSY",
	"sPeD3pxaY3K7SgFvnqJ5uWsSPuXNJ5pBuzJ/4vVzeP0XQtMrutCke687dAB8t1baHb/7rt+VtFs/Tht6",
	"4l2Othmvbje8eX6DW5C7jqY2jstueFt+JU+TeLD1msixZmpe8dvyOsm6B78+/ArWRJvNqE4HkXqA+B6n",
	"BRIjF5zmEBXTTI1uhP0noQwPknui/Vx0LvQux6Ibc+96JpwhvLG4TezgNas2vkWvnzFMQZf/2Nr9n1/3",
	"hj+8v7hIvtm+uBjd+HvrrwfDra2/HgTP/gf++ZUO/3U4/H/D97/uDn/wf2Nz6GHl9tvfbG//FT/6dit8",
	"863tqPYI2/5n6x3+tnxIoZuoDa6Vl6h0qBsP0xaXDsJ3e0ROcxqzoWY5VfZ6KlOZHti4URRXpL9SACiP",
	"iTi2XHeu39j/wfyDAflxQP53QP6x7fwBPj1Ymx8y6ppcfZd/dc1sg//9x/tvAJjvv3VQff/tVvnX9l+3",
	"hhWkR0N8cnHxbeMZ+QSdbn+zxpZuYj9yhiM0gytmCuWupiOpimmaOtdbIsUj41tIjAmw5/MePQJxq///",
	"tJgCmWYJ+fns7K2fArStPNJWvhiQXcIneD1ZN9nN4/1WEbf3Ddyrb6DjBtRhIyVO0zpbWSktHJFAdIUI",
	"K0Z1uxk4o/GMC9Y5VHnhqhzA3grGOVxEzylPC8UuolJoPXYTsijAtUuOaND5iDpe7WpZGTAxIofkBKdJ",
	"4pQqYEuY+QrR2C0W0XhcwPny6Q8rd187My5PeetBdrCsgEfeCEbk5IBcRKdFHDOtLyIiVbjST442Omfx",
	"kIpkWN2cW//CrVu4IxMlBgxuvC1WE0fWTS5VhnHUpMmto/Nn216vHZFwBO7cxdNUjq0FF3M6qkSTXMmk",
	"iKv8ot7PxJJlm1NMhWDqL9BqQaxH2xDDBBVmaHNjBhdZzuB5vLAXAIHZejd1y3VudFmxD0BllCymM3I1",
	"4/GsGuf3gilur0Mv0fNkzrVUi+MWQnnORAJCrWsSSmA2+Vp5GtqQ+fb8rZ2WvLE7xUfnz0bkeZkrI1ik",
	"vVPpJN69v9gwvhoguPG5wUTDnhFqLkQVQtggCafouKwYdnzbdWheGV7BCW4Og6pGaPy9msl0I8vMxjx2",
	"ztq2EVB1WXiGpQ33d/efDPf2Hz9p98vFc61PY6najO7np6dkTDVzZvQmOpTLnKSSmqp7uxmN0LcGxZtJ",
	"ZUrVyhG+2mHqtmDcbkDZsndeFXl38nK7YtV1LNvERJIV3tOwbCxZtX+tizZt6HWYcKQ8j9jYbegJCFHU",
	"DMjr86fbdkNKk9yKdpb7FYwO7eE8v3XTUi4u2z3ZLkMuIHCCSYI0yemUjchbkKgwg65bNjllcYHqeC6V",
	"oSmeWv/OAYwzPbDi7RXXGFf5+vxpu+/bebWTQ9MWwebA71ph2rslgJfYD4LcEBq0svvAF7K03fB9arMF",
	"ezsDRjSFYa1HlcH0Z2swfeUNpi/RYPraGkzfNQymwRRwD9czitlPVsqjgQQpWOitbBwTXa/NywFBvKPH",
	"EWAp8IBnKPzAadQDQrXTMCyLQfI/1LHMXZhzk8rX2TfGS3l5Xo/IM9B8vRE8cM/D2JYCcFExYpzlFbXM",
	"HNicDfBaM+n5ksPxJtbpL6vgCr8u1rNe3vVSVQwWDQAHoWdRLf+e067fIw1tJ5YvfL74pipGPxx1M+ef",
	"nZ9mmUm7k0HTtATdapw6ox/e3kQRX9oM5rSVMN426oYU8u9Sha6ollHKugBl3v37I5yb0L5bEtR3IN6G",
	"ag2cBE+ZnGHaX5YJZZNBYDgH2HEvKDnLkL8bjowYM6Xi3YMvSYt43Sbd45kvJXuboKuc+gpk8CsUfSdc",
	"aXPKmDhsv2gkAhJJNcHmS76cdijdeEA3kIe75eoTNtG3Cu+BA6qk+44hrED6O64jV1T9gQTwXuZtcUw4",
	"Wu6NhEjD6lv85Yq/4UGoEf0Ks1ej+hsE9r+lUy7QJeMj+pvdBqGtWzXBt826sf3JbwJUU75xquX25y5i",
	"YEMZ7vPJby95B8X7ckLta5M+dui6JgqelLYVIwkV5M0pINaVVJeppL7m09gFuoOu1SlJrFr1qcbc2Qe6",
	"FKcQMoOc2shmFAq2ygS845RqQxRNeIFFi1YNBd3EyDT6dMyzjRBF9c5X2PV8/QINP4Xwq0U/AOV2EjlC",
	"214GrypNOUntHr2LK6mfJTWp77yL//ic9rguKsnUsKWQmJJX+sayaitTynrxt5WJZHvgSQtGfSWyz2b6",
	"dM3sUHMptJd9u7uivZoYv+IsbhTT7s6d1lDe1wXkg+rxAQttUelX5Kr3L9SRWnG2zyGr3a+Y9rmudrYJ",
	"bl+bzLYcBroeolmLct3S7apzjhfLh5RhcQ0Aa5FiJI4tpoFX7cNbaYAI2xtdlirvSC2HmVdu2/oM7uce",
	"FV6fuuchb75i9VJe3feAt96+cpeu7nnYWy5m1eqjPtidrPly7EZlIXbL5yXl2nTht9/Vqq/9S76m1Wbk",
	"aE+/X6MUYxpfMqwAQ00VCIMgdVE09URB2vDJwmY/W6yY6eys+upv+FVjtncK5H6GN17b/H3eBlsJ1fem",
	"rSzdhLsx90HLnde7SObd0eCreTXCebQhUvfl341zGpdd/ER1W5K3VXJKdvZpM0y2ZRNc4UpC2YvPGaBL",
	"zQXjhgQjVOcgdPgb1c1r1lyTw7fHxG/d6EYgIgQa2w5PSXl3GgSjAgP2giQrVZ5mHC2M4rOZdfDCGWwP",
	"mnCSJPQZYWYpOJjNQwCq9JmiQltg8q5aJKhyo9nYhci5uZryW5bYUBkAmguhRGMSqnDrqC4dcaqYe4GU",
	"oaM+X78rAwAw8ltHx7Iwbsbl9FolQq95vWDCBWW2r35U1uCeli2r+kAVNECnA6kK1MyEFPnKMWPdMbNb",
	"mDthm9gWVVJdP+YjvdJKV6tR24m3HVVry8DPFjRaMQz0tiFviaYt4TCwMSMTcqYKNiDPkVeQd9XFRs/F",
	"zmy6O2xwk3bZnrazPjvX19JT3/XS43Kkm1Z9SzLTEtN4GFserO4wz5WcMyD2Z29fnTOMbU6wOHf54ikT",
	"9tlzLNzWbIqxyNzmvq398ETuLVUam54uRIx/nNOUw/8nQLEKcyzeKjlVttb7uzzBAwrtcxb7pq9cUqY3",
	"V4IpHfnrn09ZLLOMa+Bc9iM0bz1lqaFvFcup2x3feunxM6FkmmZMmJ+lvNQr7mv11YkN6g/A1XhXh9YR",
	"ENMJliI55VOYcrOLzjblVnS2KPeos0V9Oicsl5obqRatOwcb1vmisb3hy3Kr7WUyt4n4o23T7fYEW28f",
	"hAhgn3waNLCPG8jQcvRK7b413xUWIKjyEHk+YIm/XggzY4bHgTEFUzrO6JyFwRkp18anVFVcFrq8UeEu",
	"6pDDytaR0QV2YNVyR9U+VvUQBsRP7Lo1R4zhomihIa9c6lRmCLe0s9BM4W9KUp5x4zOVVhHXtqKej7ob",
	"WEt1WXenZIDIRBXeFcaIPYRQcNkC9Q5/RUPm9PfCGr1dNtdC24SwaID3EoO/XeOtysFFHIC8NZii9IUG",
	"NiNhmoqzuZVQBPtgDRxyEqZi9eA+smByZQ+l0FwbkOuwL5iWu8uTS3tQPMjcSuupqGDd8YyKqfXHIgjM",
	"jGI5RHZFMi4KABfuaU61ZokFid9xJ6a7kthljCM6HWwudFsYwm2tA+UVT1OYovWQxDT1kHKQdiYBtDB7",
	"J8mAFAKNsQtZ2PkoFjNegtLISyZckUdBmFKwHMu8O676ZLZWks2TV7RlyT2rYZQuxho2Vph6uUYEvA22",
	"9Bcr7PEJoluwTenvsZd/mH9qkcWn/kpsvC1aoBGqmqUsNlJprAC5jOflOvykypQIvj6q68YDPWUTQwqh",
	"XdlNmXFjWEKSAk2amilOU39roDZR3McsT5lhZIvZeoFjFtNCM3cZAZYezwpxCT3J6q2/NWG8NI6Ntqv1",
	"KOZAZzFweU12IVzfZSX+tpzEEtmI4/O90d53JJH+bl8whsXysqgjLKIsVLWMN7Cyb5g2PEN+8Y09bfxf",
	"zKXGkinsH07iCG/haaJnskhtyVPFkFJ29W1zYWvrkXCJsT84/9YqRptbhdagak8zSXJVyIYvMxCapiSH",
	"04+XKFuZiD0T3OelhC8cFUP67drGilHTlspCCGkzoN0lBXnV2Go3i5IWuvwZzeLFMB+nCWhDs7ydLpQK",
	"pTPtg/5kl5KsrjEmLGWbjOUOAH6+znjTG5TFQ2KpW1xSl5pjI9DJA0WyLPGpMQcs2hZG5K3Mi5Sa6s6Y",
	"rRs+IieMJpgdd1U7NuZSvTHLNf3gs1x//3jVNNfOfXOJWeSrZPFhlXDP2F2EkmX6rvAC/NyyMR3w1NLn",
	"7fDmcgOpxEqVUm176CBY1v53beuSV6ItOuAw9DtRQ+SVcGUG/HOQ7cgFWtV2YOyLqLuudVXp9byrLOqh",
	"8FKRA6qtg+pDH3QgejxyqZKDDMxIIUWw7hXyGi4TsLfUxDOnT8D8Sg/gGvlIZMfBqy7zGgnUDiAVqqw0",
	"SaIyzTf+lck5nrx68EsQ7EjNrG3bsPA5BhswRaBRe3VaQNQO4ziKTs6AJpXPKDxqGD5kHrlptNk0GjkS",
	"tQt3wKLsFlpjRhVTh4Vdif313B/m//r7WTSI0CoDHdm31VpmxmBMnFTTtrgZWMm7d8dPyxMRZkUMMZoF",
	"IXCvaO4MdrX2FccaAaKjd1hgFTCmFpE/kzCTf6JO55ee818YrP16YAvf+yz0NkwJWHQaHUSG0ez/TlI+",
	"nZnYpCMuqx5hEc/xDQrrSqbkjNEMy5ClDgb6YGen9nWDVv1a7+L9Vttn284fbfmZTbDK4pQC1s5ZWOJA",
	"TnxElJxgDurqBk9ZRt9HzenRhbgQZ94+7A/r1nyPpvmM7m1XNmd8MNTGRqB5IcBKCIqBzIwcy0inZtir",
	"RymPmfOXOJgd5jSeMbKPKTXqYLq6uhpRfD2SarrjvtU7L4+Pnr0+fTbcH+2OZiZLEX25wXwdS+A/fHtc",
	"qwrkF4KYaOlIdBA9Hu2O9tzhQETfcVlIS5IyZaYjt3SYmTf0+IUJp0tqApiPnx2mafghjq1oxgxTGn0V",
	"LcS2LEDhGgJsbdC5k511kZogDYQlvqEm685W1UNQy8Est3rkdbdHTvr2oY2KzdEcUFdtOg5Zqds70kBb",
	"RLfrQZtIYnUfqyRDy9hUGgmqP07l9JKllTi4cnnYsQwhZjXHanFzphZm5pyDbRPFr07dqA84W5ucfeDz",
	"AaMC5XLZAIgvGXn046MBefQj/Asn9tF//PioTJ0TXbLF3o+4b3uDS7bY/w/7Y9/VI2lbKY642UoBlTL6",
	"gWdFVtNELeaViwz140r3PatsESjHWsWrG9FqnxM+qaM5+8C1sZ0uGRkyurD6JehPVnRlCaE6wHsugHZW",
	"aj1CqBMzeMZNDU6NPDAOJtHB3u7uLpYUsT93W1QzLG9mF4WkZX9313MaV7GH5nnKbVWmnf92LpZq8BVL",
	"O2H8F/KyJdXuF6B9T+5x0NLP0hjrJ5oQL6DhoHsPMOg7QQszQ2E9saM+foBRn0s15knC0Nv+ZP+HBxjy",
	"TEryioqFB7GGob97kNWeOrHjnSjtlFZmp1Ndq697PYg+DL14AOwg5KvXg5LRrsZk6xGITa7qee5nYKc9",
	"N+25ac9N/y25ac9Je076RXDSXLbd2jpC2zOhDSbZ5JG2qa9sZK1DTJufZLK470Nj11qZn4wq2HXjrO59",
	"mmHbAJRE9hoQjlwDhE96UIdV3GhSFyo+lltzABNzZHksk8Wfdrz5Ce2suJ1P0WDvJ9kYLKm9Xh7IUc7b",
	"R3nBTOcQ0+rdPfRfBTp1jXLqw6w2HCuQ5469FaY+Vrrc4i4bdGKtpp3gU/X3Gy+rPk4XGFVbqw3HvO6Z",
	"1KdmUrsPwaSOpJik3Brre7Z4i4JZVy53Prq/rnfWtejauBL/7Ea1cyVL7rLnr41pV9mnWTJlQ5rn2gvT",
	"6L6p1MEaJ68Y7Xr61h2U4S9OTb1/dfQuSlpvUOw5zD1xmCcPMORrachzWYikZzEbaV5wSqwxpJNdHN2i",
	"VXx5/OL9J1UTbabDFryolopQrYJbZBA39uDqZdd0W1TMmsbXrmImjSY3ajC4CSMMEak2cgPdrX0y0/r7",
	"TziTugrUPhvVbPPJZtQrSP+O7OvBdbKvRDHaafreltWjnY9wMq4twwMS1ZYSC6PB66zvNl3p6S307itQ",
	"ljpmVONRo/bx8b+1Oe8nkuu7EawX5/8t6eGXR51aDTAv8GbXOkTlxU1yS09RHoyi3CIh92SlJysPo6pT",
	"E8/aMoqZeLaWqo5f/NuTFrzfACu9Vxqzqr1giEN/ux6e3HgPZCW3c0/1eqrXK5d3pLOFacsFhWabtejs",
	"yW2mnl6I+8INsuWNsy+O8n4GE3BP73t63xsTG8bEnYTlqVxkMLPO8IsXLoY5OGpPq89cwvecKsPjIqWq",
	"JPyOadxkGAj66dnLg8WHfI13D/uo/K8mJKU61H1wSm92+gLZY8j06kxybQ/bDWH9T2+IHl+buwFlt3Pq",
	"/Vj9ye9F8T4Qbj2n3Q106kXXFZSNiNTU5sz/SvxiPYnqI2f/kJGzK7njbiAaoRvuPshG7+zqSVlPynpp",
	"66sgnm0+NkxPvppieHLTpdWNqGeBg38drqwvjjw+8H33niD3BLknyA9+1di6u6raNZ0qsy6LwqynPLem",
	"A9jIi9Xrzj1963Xnr1N3Xo96hFr0F0g/ehW6p2g9RftjK7TrEbST2zMkfR0k7etXa3uS1SuZvZL5EErm",
	"UoHxm9NYJVwbLmLTVZa8UWXDluOdTFiMxbSwSERQiLqZ9+p8aTp9EYM/aCLj5whaI4mWyixVNPcAxm0d",
	"dwYgwpc/LWrDJjbjNLz0xb+rAjzBo3iu9WksFWxPXoxTrmcsOTS2dPhx0lKNp7mCU5i4VAlTZbViN+fu",
	"6jEJUx3zhb7DYkH4Cx+uMpc+APXLDkCtlbZ/oWSRd0efjj6LgDT6PBLS6DOISKPPKD6MrPyw90Dy2XGW",
	"p1jSiSVkq05kJ4xi7X1XipMJEDASW12Sa0cQtkefVd4Z1QSe2vybYs+ypNMi/ezEc6Z3PiKNv97hWe7q",
	"dLVKRCdINUnO1BCLYSHLxL+wtOwYi5MqmvDCXzM5On9WVbNTrfb4GiE4thNYQQWt90y2YDx3n2QAL4f7",
	"u/tPhnv7j59sj3wx+OADTbQBym4ZAdnf3XWSmyAsyz3HBTXai3JVea6tcKHbtlqvkFZ4AhEDq3xyAEEh",
	"kg512DLV/krJGus9cbKfQ7ShQzQlr1Dic6I2VnYkYzaB5dPpVLGpL2FrhUCWkEu2gP35Ddv+RrZqn9oJ",
	"DEiAUK7lj1iHfCdbWOz/bXtE3pTSpKvTSn778bcB+e1H/Pc/4F9b49IMtVlAT1z8RnbIb0Ia+OvKFu+1",
	"tAOP9ycWK2tn1IFuI2nSnwtbbl2HglrjDYLrNXTaS5G9FPnJpEjHPHoRshchv3gR8n6FOFeLNLgQ1W3R",
	"ahiykFy7GtVcTFNf2jRgqmXtcl8JtiHFWWK/pi0LqWtYZNaLGba3/lZub0zrjWm9GNSLQWuJQb0d7TML",
	"QQ/ra+wFry9G8NrRRZZRtbjNgGalCMstiPvGGczqEtgVNzNZGDJhzrQEX06KNEXzFxDKFYWxxamb2Rcv",
	"kf27Siifkvx37/eJG7LnBz0/6PnBp+cHaOncUA93tmqWOFZgXSzjhfvjdh0czdP3pYJjZ70G3mvgvQbe",
	"a+C9Bt6Hs/RiVy92fRVi1/1p4Vbw2lAJb0hjd9bBH0ok61Xw9U9M5273GnjPCnpW8HCsYEXiH97ZGF7x",
	"xAYU2nsaQM08Y7g9ZLGi6g8jXPZ0pQ93+SOd8etBZPuxslKh0ugg2qE535nvRcDTXcfLB/2NP7Ua5rN8",
	"SxVV+KXs8k1RKOgDBMP64hUDCUejFNMkJ5YO8dpA9aVfv7/+/wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
