// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3Lbtrbor+DynJkku5L8SlLHd/bso9hOojayHT/Sk1a+OxAJSahJgAVAy0pPZs4/",
	"3PuF50vu4EWCJKh30nZP9p5pLOK1ACwsrDd+D0KapJQgInhw9HvAwwlKoPozpAz9835viATc+ydNEYEp",
	"/md3yGmcCXQBxURWihAPGU4FpiQ4Ci5RyhCXfQFIADR1wQjHCKRQTDpBK0gZTRETGKlBUm8/1xNUtJZV",
	"gKAA6n4oAWKCAJ9xgZIOOKMCATGBAkAyA+gBc4HJWFed4jgGQwToPWJThoVAREKAHmCSxig4CnbuIduJ",
	"6XgHpmknpuOgFYhZKku4YJiMg8+f8y90+CsKRfC51bAwKX6PGFfwV6fTveiZMhChESaIqync628oAnrV",
	"AR0BMcEcMLuMUHYgP0MC9PgdcIWYbAj4hGZxBEJK7hETgKGQjgn+lPfG5ZrJYWIoEBcAE4EYgTG4h3GG",
	"WgCSCCRwBhiS/YKMOD2oKrwD+pQhgMmIHoGJECk/2tkZY9G5O+QdTHdCmiQZwWK2E1IiGB5mgjK+E6F7",
	"FO9wPG5DFk6wQKHIGNqBKW4rYImcFO8k0b8xxGnGQsTVrpAsCY5+CczCBq1gFOPxRIQiloMVn4Pb6i61",
	"goe2bN6+h4zARGLWL0GxIe/zpsW3V7bvHvUVnyapmMmBHtpj2q7gRCMGpNeqog+bZRd6fxGAaRrjUO2t",
	"O3F1EDkKWsFvGYxiJAI5EBEQE8SCVjBBcRK0gvtk6QVQ8Bzn3ZoP7/Le8xrFIObTGz2W+fU+CW7nzNpO",
	"RvaDiJALAOP4fBQc/fJ78O8MjYKj4N92CjqzYxB0x9vhKxwj29Pn1hodXKIYCnyvSZTsgaHfMsxQJBdF",
	"0Zvb2qFeZnoniMtergQUnk02pSDGIxTOwhgBLiuCEWWKFvr3nGWE6A3kgqYpipbfWx9Yl3l3DRWu7ChL",
	"zPeU3L+HTFPpEs1GRQGMIizrwviiVKV2YsqLdUruMaMkQUSAe8gwHMYI3KFZWxEekELMeAtgIjcHRSDK",
	"ZDeAZUTgBHWAPFB3aKZImG6BYDgBScaFJPdDJKYIEbCnKuw/OwDhBDIYCsQUpans/QokPl+bC8pEHQfk",
	"V5DANJXQYiL3PoECDIIJ5UIWHuXnWf4aBOAx6ow7LTAIDncPd48OdwfBk/INZb7LexMKScCDo+D/DAbR",
	"d0fyP/9ev7CWgJ3Rexwh9hJyDx4f0yShBBQ7rjE4jl0UVuSM129zSAjVl9Ym2NFlQywYZDOQIAEjKCBw",
	"Ou6AG46i/DqLZ2A4U2RVXUI0BmkMCbIrW7pDppTdxRRGiqA/AdMJIkAwSLjcKLlntSkCKG9WEiEGFOoF",
	"rYAhGJ2TeBYcCZYhD+7A4h5YmXbZO0SvSYncbEBSm4jY59vWClRMsSbOCrUA5CChXPEeiIh4BjgSdjck",
	"PdvhAjIBInSPQwS6Fz3eAZcIRm1K4tkRCNWuyhMr20WYoVDo7ZSjzP43kNWAYYXkeZL96t1AUWmveIpC",
	"EKEY36siw/jAMSKivmWfW4Gkow1cp9OrrJUTlb3/+e//WyYlIKZk3AJ6jlMsJgCCGMlDCigDJEuGiGk2",
	"y5x6QCiYSoaIpzBEHd/ZZUh19xoRxKDwMpPHNJOoDzAJGZIUFEV2zU1rZ8E1YZSoW+U8gOIzVX0U/Rm2",
	"JV8NebLHiCnC7F7d9lzdrkOvDc27SlGolhTLJU0wgYIy+cFQbS33aIap4YQZfsrpvMSnNbYyFcrtFE/X",
	"0ETyYOXali9saGAYu3Kb+8b+35d6/5zT8tmZOh35en9uBZSgdWmPZ7nW4uo8k1urH+9GrNVTdX/W6qSy",
	"CcvwZZdGanqLE6yF9qoQrstBrCoY2l0TO8o3d5hmHlJzcaM7kadcgsU74JXmaSTpYFhxZ0Mo72NKardn",
	"mZPZ7Xz/zEfyEpRQNqsP3lffzfiKvNJUMxNACp0bQLL/7HmykaRf24p5uxBSwgWDmCy7FXG+r5tc9BUs",
	"WWt6kkvIuF+o1WVKNwE4JuO4fLsYLY2+iVyJ54KhFBrB5krePvrPQnI5ZYxKSfSG3BE6lSRMkpAYCRSp",
	"JlqAMX/JJitLTBp0F5BaoQNZrcwrZOkiC3utoJhMrcidnQcOO11/kZr/Ejt5wxGrC3IsI13u54MyjtTa",
	"WZ2FVrepzzVG0KqihkiKaCCTnIAU0jCXTIbkJVQPsjeoNV+qG3mmMVFqu/z65B4dCXiMR/b3MEZPOuAE",
	"jWAWi1zDZaCCouAvJCRcDvd4rHgpKScwSsUTgEcKJMmb4BFGUZ0PK2t9bsxKuJ/b/A6nbUuP2ilV0ohh",
	"L9c5ae9pnCUVNr/KmWvFIVRsaQTuVQs5dcX+1VUM5a32c7w3BP+WIeButNuv2SEPxfIwrmEMcXJBYxzO",
	"NqVdejUuS11WuUE1IQ8r+PsmzEovgWOkRy9xjGtd7X3JqG+rMwVZY4+3SzEOnpY1kqC330MU3mIuFLV3",
	"DqapLBECC5Tw7ex7UBwgyBicBRucqMsqWkaadKgLWpKcoNVwziZ06lCTCSRRrE6fOR9adzBBgE5JVXOg",
	"JKuE3mvaYi8+M97tGhobPRdN9uffxFuhCmc1ctBw5EeIIRIiH/NjiiyFjlAa0xmKwPlxry0xI8ZQCo8S",
	"q6W0LG/bEQwFGMLwTq7n3LF9pMCFZx0JkV9lSQLZbEmep6wP4838zhsEYzGZBa3gBI0ZjNRlXudxzqgL",
	"y+o8TRn8YtDGKg40jXU87Ey5gpetKVepTqxpK46hgDEd9wRKLtFojuhekVtKzdYiQOWRNUGtYFhllKXx",
	"y9N1o1p0BGOOaqpQwNyjBIGBBEh62wIwpmSshSMp6YWUjPA4Y00ynm7rZ/hsx4oXyHkpOYykZylkkvp7",
	"6UA4gYSg2GP2JI7IlkZQIGDqgukEh5PcPqvIlaAg1VudV84Q14QW3kMcS+bPC4AE0j8pl7FxV06uFor9",
	"07lvtOKCexjjyJpt9SKFGWNa96lMz9zqw9zRFlMwuzNmLgUQy2Oa3OaRPDLoCo/llXSJfssQ91gpGqsW",
	"dmd50THzUan/AcdjgiIQFm3BiNFEzfW467EElMzhazAFefPPreAOk6g+jx8xiSRuQqBX1ZiC8knYa+Ty",
	"9OoaWFOzFl70YjrzLczqCZwBTEZWzMkniUik2Hy9uzGWXAHPhkrDYpZKyiMdcJyrTzUaRx3QI+AYJig+",
	"hhx9caO6slu05ZLxjl/fom0qa+3LuVq4PhJQdsUNQVud5DahoGGQA57zOlvsW/dZVyvnqGYwzVkjM8fN",
	"j2GueC6h8E8MpimS7A/NSASgkmTbIUMSb8Dx1WULJDRCsdZq3WVDxAgSiANMFb7AFHecI8k793uduSDU",
	"Dyp6SLG+MK5QSEnkVWWp9toQm7ukKGKIxSxXajmAyGG08VPr8w/2g7p6vxWgB8HgPENhLlXUsLgsINTs",
	"y7JjAIU+PyjXKhSKArvGin7JdU5pmsXQMaZ0L3qAK6Ig117VlzOHkugkSSYq11GBGKyJ8MobaQg5ev60",
	"jUhIIxSBi9N+8fePx1f/trcrwemAPhThxPgJSRTs5OQYoziStwx08WEeTdeEr7Qlw5lAPtqgqDw780oF",
	"PRJpJDP2HosTuo02dClq/FsGY6VZUdevHDfB5C0iYzEJjvY8o2bYQ91veidfYdccIDgc++TeG/U9Vxep",
	"6wYpSfgOzYBu5ayGuf4x51n5uiwJyQvR2arf5gtnX2FhKsTS4nYJVbZAHRtE2wLnYCqZQxjvRIhgGO+M",
	"II4zps3TWX6+1dQdiytv2AyAR4W7oMePwanqP8amyzpX1CpWE1DJtecbsdQBlBQY5/4TVcOvLdOiZ2FR",
	"NbvSAT9KaQyETkWGQFctHYpa4AQRLP+VK/QK4lgDtb7qJofIq7IpMbjFvJbHlrrlcGtuECUfmLUUch5H",
	"qU37adAVbqrPbJKl1zOfLiWmr6fiJDEmzdDefl4BcyxeboYweT85mqQeP6ZNOtYG9sphEX4vh5qzTt5L",
	"Qe4iJCCOtaGREgSgvLdELgJrYdX49FhvY3kzXOZcwsI19buNya8F4ZESWaYkFDCicUynUhb7sWBX5JCu",
	"2AJuODIuNHK3lKojkvywuXZD7T+LSJZ47KWQi2sGCdcriptce2S9whWmgFXkbVGk5T25cuZikZAQKiaI",
	"lei3FOzasi+/hMUlW1CH4k2WQAIYgpG6H0w9gPUtJ9fI7h8c0kwYiHPwvHwLHapbPZrnMiRn37EyTWec",
	"1yz0PMVqTCHXblzKlp6leliXmX/+1MvMMwS5X23yeMgwGj0BukYhL9gxH/GlZrqJTGiHapABTdctHy7l",
	"Mys2dnVCtFh3X1qRlkJBOgLXLEMt8EqpBoHRtrraZVketAJVwdEnL6c+rkBn+qp8tV1XPucjLZx6g0+8",
	"8YcvEA+7ShJnipZ9CVrB9UX/PWJKttAqZ1ugGRu1EJKrqVcNQ8Q5Hsao+sMSvgvIuHYrmJFQ/fFeyrey",
	"hiRgmejJ62jMEJdocpNG0LgHyMvJVu1nscBpjM6nBDGu4LrHITpBIU0SzDmmxnHgVYyQOEGxgK4Xgq1d",
	"+rzcVp4SRuM4QUQYjtpZnFpZeW0amXKni8Y6+cI31sh3pLFGGZxLlFKOBWUz7z7J7WksqG2mW5hvrFp8",
	"u2Xqh2+L9WY4G60/uNutv3yRTZ9zqkZ4XDWJbMAhvsbC0+da/Ftxv1+hkCGxLY5wW/C9ESL19TVvseuu",
	"gv/aIojyE/omx7i4UWX6U8p8Xpdu7Mf2PCJUnIlHP8Rcx8NtuAl6PQSX53PSzHbUp0RS79zWmZ+V8iom",
	"utrigLnCcEOBabRYTeX27vURWiOorD69OZSDUXL6kMqrxO/DzygBKK9gA4UkZyyhiLJYGa9wgnhnQORy",
	"mBqYg49/A+b/H49AG/QxyQTiR+Dj3z6CxGiNd9vPXnRAG7yhGasV7R/IohM4k8vbp0RMyjX22gd7soa3",
	"aG/fafwTQnfV3p93BuQqS+UpQRGQWw4FlUC0ZcWjXLENycwY7EykjuwGEzCRIOf9oXvEZurbEznux/bH",
	"I3AJybhotds+/KgWbm8fdPsSSw5Bt69rtz4eAeW3ZCvvtfb2TW0ulBpsb19MQKLWULfZ+XgErgRKC7B2",
	"bBsNTLXFlXZ+Lc/lsFgSydgfOk0G5FR7IsuVA7vtw9be8/b+gdnSztIRXccZFzTR7EOPjOg8O0pVIlNm",
	"Jh2KHIFQdWQjvsyueOGoasadTjDRGKp0ykp4LbvDLEdHFBtUSLKF1LSCy8QFxAyENCOCg8ehda7dEVTA",
	"+ImxZqeK00IqRk8FiHXABWLtVDZNJ5AjedCkCFYByPKHEhWIACligAuUtpRHKZS/Q+UthiATQwRFBxQ6",
	"GiM8chBCxmaFS2wFRAO6Ryed+wnXbQIq1kieyF+p2g1HxFexlCZAniEAY4ZgNAMCsQQTGC8p3Eu5+Eab",
	"sz3kGhcmCSXIV6c0ZdiNITOrv7xCRfUyb9qZ9mOtTVtZYxpGbJpsTXNduGdrOG6Xx+YUkQiRcCZlD816",
	"XqLRWlg9ty/XcaMUjDXCZIxYyjAp/DgUtdKeQtbhhj3iAD2Y9ABRPpIPB132+awxiq7kd1MeSpNIVTLG",
	"AlAG3lxfX9ha5q6X7Z94SZAzI//Q7pQNBPlyhDqs3IAgh1cymgBXb7otwCdw/9lz2UhBNKTRrAV+POSA",
	"K3Em15EabwE/fM5B6Ypl9JAuvOFEXm0ReIw7qGP9Js1m5MBPIbeeJU+WPUJ1a0x1G9dE6i3gsh+F+YyE",
	"E0YJ/qTPs7NMWrtdx1eMjBOsvnVaIISpyFRMYi2I14fWl2jk4+sRa+vydo7C7p5JJkLtqHFakyO0lAY1",
	"dxE24ZgahA1lg/k0ZX3Pac1HrLyRZmKO21g6mXEcqn3JXWFt5FXZLawpv4f29jKdB2WHpRgOUaxWbhQj",
	"FQlpHbrzqN5g9Hw/Gg2fjp5F+2E0HL44OHhx8Hx/+Gy0dzjaD9H+88Po+2fPn74YRuHh7u7uwWgX7T7d",
	"f7EPv0ejw/BALdo3Z7ZvzmzLH0mrGNzQSmE6WsNN7Xa1Y16LJav7VW8piQFKhiiKfEzjTxMkJoj5wtJt",
	"I+tMM6RUhDpWwEGCIaUxgsReuopT32DZVXu5MLOClvo9cCpWPJfXWRwlBaNZA8uUM7NOMJx2k5Z8u+ba",
	"lw7GUnH9fB7LbOsAa0BsCk71WPq2FDaIOWCZip4xIYO9ERjGkNy1vMkKMmLDB5XcpPo0H3SQTjXUb+uR",
	"fRudbn9c7edWc8hVYRw0VfK4nupSbjkCaw434Y27kUjtYF2rsKfm57+1evqGGq0qB5b49BpcV7DYN1Fh",
	"MJWoNU+sTpn0YaNMmXvqXX2HNtrbG1oxg6UA9C9m1p4fvtRg5F5x/Y9hCoc4xvnFsDx76DaV7IlWCRp/",
	"RMMU58lAyntAeZ9G690+56ppvgIrzVWx003odex4zxQ2ezMPLSLUJ2Jlz8bcgJdWOLVhJU39LnLMLI9z",
	"u/LMOY29ac2c4qqQFprPISUEhcaKn5+L+mJwre7unfgvD1MMeieuj0hlBP8Z0i37DjdYIQ051uaj5Lml",
	"zKUq4TZuvX8vpSELIXGDlDDBAsMYf9Lye57YzyjUWjnMgtpmLYBE2LSH5Rw4pQNbmVXLWcAV99e1RvtS",
	"bdg0W0pzayVoEJVt2LmfaW1jBWRjJDbivoqRrlVnfs84Pc4Gk3c6r9+3uY+3PoA6FVZ1ERIkJjQqH1PX",
	"X+WGIOVwobxRQkHZ7BLxEtDzHDnmQez0PK9aedRFS1Phelej8JeIZ3GuZ3NygYFIdqwTRgEoBEpSUSiA",
	"rapEgVzHphGM4yEM7y4bPMquXOWKO6jpNx8PxbEKKNaCLzRA6VSyWRyb8OM0i+MO6A51OqsRINRUnEJu",
	"+0IRMBRJF/EsDBGKpDx8HCMo8SSHiKCHOih26nrOOmmYX6Tl+JMHN08fUpMLUY8vyQ8moHd6rLLhcPD4",
	"R/yyBfryP6/lfygD1/jlk3xiOXi6qc7LMUMC5D5l6+bDsSYogcYMi9nxBIV3TXdoc92aArB0y2LbAoSy",
	"CUgRk/Rax0Wtycy1vcxcYbyqjqkh2jYP17wiW2TiGrtf4JC4wrIX5M+GhN8Qbu3Armde7uu1CkH0TaAY",
	"aV4dF4bmejl0zVUKuJdc60afTyOkNGF47WZJK7ZcNUqEiMBitmWcU+HUq8o/xZFRsk8xkwWSj6ydr6rX",
	"qsgFTNKSabHo/F61LOTf5UyJ2zupJguT3kwry4s02fqObJcC1MFemgY0sjyO+2Z+kPx0YK0zXzl/LX95",
	"0xFeQCzqdGLB+X5rU6OuJSfmiVW3oHeo+llUsrZ+qbuqsgBbvKZ8PTdhp5tQ3be29ftI+0EbFKk657pf",
	"VsTTCtRVTKsUl6DwlPtAW1BtMc6e87o/3npOmOfMly6l5iSpuFTVoL6B5zYnyAQTcaQyTZRSnBjRwWYE",
	"qqV2fsRdRw+GQsoiboNokLJ5DZGTME72ylQe3I+K4f9o7WCYG8x5xPPQKG1lsExzRJFmlHEiBZlcMjC5",
	"Pv7nv/+fi3+YWFu0iGcgwjykygoXQhJhJQ6Up8aNI4L6ykGaDWPMJyZzk3HLUr4ZdErAce8JYGgMWRQj",
	"zvPgLRUOriM6pdjEtbxTiDhSuNEJe5VkQxTrn/HmaN9FQWenWJltnNCs8+OekaTyjVTiB5yXu6aSRUWr",
	"WBjiNL7XahZIyh13goUovg49Pr/yEGI/3r4vK+jOr2omKScljSw5wePGPACRKqv2ZRBCe6Icwd1Op9Ps",
	"ZrJ9i1eFiOt1KE9mRYqeB2CstDe5d/MiXthkrV1zAcrA5XnXMb/beqdFktstdlv16kmzIB/JzGOj7Zrv",
	"nM1L3tl6A8svuRRZyH6CzFxmxwwLHMLYkwRtlTu3DKibY61eWgzuK3UA8hVbIH1lC2PgHM+ABk3Ilc6Q",
	"LguGKrdEE6a7BqzlkjNab6UtBiOUoy5qQQnaVtEMXcUTkG+cfKAeFuSDidMYNZirY7tuocD3hbXBqNk3",
	"dtVyLSvenDVlVm876nMVFLwJxIZZrEaZVN/oYDoGIKcAJuainIRuwyWsRF34FlF7GEQrKq6vc9+ESGVF",
	"wfKyKUeYVOJVoAgnF/oJFq/p2aKSqgjMYy3l6des1doX18KRESyUN0nLpDvXKZKljMez0Qg/GK6KT1Ac",
	"t7mYxQiMYzq0gyn41ehwDDHhbnK6mMII6SEUTAl8sBl59p89Lz0u88tu+wVsf+q2fz4aDNr/7AzU/34Z",
	"DG7/12DQHgz+Nhj84/a7x/+xXL0n/3g8GHR+0RV9xd4nbBY7MWr9+gbphp34TtNNnvlxlRtzTQfYoqmr",
	"9/YL99zJ72quB2DaSllHMIhj7QUTigzGRXaHTW8Ta6J3M3071/ymlLHuheY53rDu4rCdISvOJHKXK54O",
	"6xJ8t5vlU/rkaKCzCiunLOuvIrfSm7/D3eEvksbHvdTXvwALpwp165VCatbs2RcnpDp33aO34GHtqsWN",
	"xnB7ymMryV0hRJaJFTAHUqfoQCR/aklfYODx2fn16ZGNeDHRXMbSx5DIGCmlA1s2esB4x/3KKWnjMaEM",
	"5e5wucZte+rEbbAveUebhcl6RVjJcmxMh2q0R/MANoxv3V6LTsqMkZ+8l/iO7RB2DUF0Q7BoJulZEUe2",
	"0a0dNagtHIJbWtjyZRL47xYXZ9wznxNChZ3FJApscE/DimL3+n6NDlWYQBZNVYgfsXG3mIytB27pqdXt",
	"+zsaGGzSpC/m8ehZry3aH1ZKAe83hZ2rlBX+bO+XaEipySZyQaeIoeh8NCrZyrpTiIVKjWI83nTmnVGM",
	"Q3EBM76iaaI0IQe0WpkDrae0rAQpFblz8hSXpukprxpLSoW+xfBUq67Pgj0uUdrlAqZzi4U5TE5iWfSQ",
	"Ul5cq9qddUBOYThRCUJDyhjiKSURN0pwKx7rU2WC2HLec9YZkMWh13oSpUMZ0jjWHkJ5lE8j9y+BbHRI",
	"lWxHV/nTGxW99wy7gTsNfTg1Grx/vT1LfPJ5iL6kVIDeyapdhY0Ttfp8t8OPOtak3TZz/1j2nzKRKMYm",
	"RLiAcVy4hlmTRkiTRBtkcOy3wWrbztrXfS3037LVpzEeq7xIc8JtcquXsrqElPAsQcrWou1QHZV0zHng",
	"JMRtbbcaYiIvIR1PLRelozOT6bpYmIXpgPMEC2Fd4iABNI4QM0EauUlNL7uJgUVx5A/toSFWzP5qu1jA",
	"3LSTRY3NdzO/bPWx9B+H8/xGvrI38pJ4XA0Ec09eflzqULTK53zFq7CmGFngLZuqmsrPMYEEjnUyQ4Vm",
	"mlVS7zmHcRbJErUF5rvzelhEp8RoquSKmyy3HhcoU+9K50pZT/rQM8y7yBnTrXb6eZ1Vj9ayZGrot+pW",
	"4rJ21mf3C7N2pRXYImtX73cFx5JiaXOvkvSankCVw/k8E+cj87eTLm4dq1YJSGcIT6k7qrdxJW9duXSh",
	"4Qrzu4UJnbaTQ6n1J8sM5SVyRvupqJvuQNE3zO90Bvj6qUuhmDRZ/hlSDvpA1nGAV92X+5w/FzWGJ09w",
	"465m8xLEJvABJ1lSvPEA45hO3bhQHeEjaJ7fRb/EnzcoCHn+uCKAKicAlSTj3vgSImaSAltPF6Xf0m+6",
	"Fpmj8o8qifkR+Mh1EiauX6logY+J/qDzKskPE/1BZZDqlF/Mf/yPo1/22i9uB4Pob0/+MRhEv/Bkcrv8",
	"8/mnJKTy5lomcASZuhpRVdiQ2lkoYKHlzd1WLUVJY/0anX4gYum0n3qoC9PY/n5pOmmeTiUlqCfgoFpl",
	"zutAJje/RA0doVJSTK+X/qEOYjna3yR72DuInh/sR4fPD74/CCFEEXz+NIJPd5/tj148+34E4fdP90fh",
	"97vPdnf3n3//9HAYfv9i9/mz8PBw70W0N9x1I/9DzoKjoC3/9/L0de8MHJ9eXvde9Y6716fg8vTdzenV",
	"tSodkH6v9/Llr8cv2bvey+7Jy7f9m7vp5fTDyft3705Od7sP/f13+/1PP9ydn3z4dPbp7NcPP72Kf359",
	"un/2+nJydtLdG5B+8uHZ2XWUfPjp9ODs5Ifkw6dwenbdnfZ//XBwdjLBHz6Fz/onH/Y+fBo/7V/Hd/2f",
	"etP+q7vp6fTDmx/pz70B+fTr7nH33Yee/PXp192T7rvw5N24e/rmZf/4YPfs8ofrHw7OfjqPEX7x4ae7",
	"l/2d/id6dvJ61r/8Mft0urszIOGPd7P/fP8Denjz2+5Dj+zvfzg+Ozv4+eTs4WH60/O38bvxAf71Nbm/",
	"Eu/Oh8+73X6Xvj4+/u31Vf/pi5fd/vGAdHfH3f7pzXHv3ckVe8DP71h0/GP49ngS9V8eTL/v/ZacxD9P",
	"Lk9fD9/0j0+v3pPnnF90e+Of3373jv0gpgNyePkde5pi+OH+5zvB+N3B7LiXfTqY9L6P6YfkPy8OosO/",
	"D4ha9tOzkzlb8i1vx7e8HSt1U6MwW0jhUe/zKzw61ZD82ZcyrbFq8YSAXxTIabxjdTTEPlHPLTeFhkKb",
	"RXrO4y5TJxeIvVgmkIMhQgTYDppSf9iEQE2qvAWqtLeqA3l1qWd9SmFNoCe5zDSGITLV5GFUKo/HJu/Q",
	"kxbQIKgsHQliY/NuslZ32JxRka3lHOXa2nmHU2HB7hiKoYA2AFszYmCEdWizAMpCp16k9Y3f8GCVM2bp",
	"kVx/WL92xi62rb4AlNmJqDfDzAO5CoHULL/sGq66ZErX4B1J5YhUJk8v+tUOtUH1zU+u41ayvrzVTBfq",
	"gs4CSBaRB8dHZVNC0ZQ2TwkEUJicOC6pUHG6DpVYLhLMtng5W5zD0NRdQr50em25U1riOZdFW7CGo5Bn",
	"4YuDuDxW+hWA3mqaF3IqanBqdR+5odA+tZVixn374nsyz33ai+vHBVxE81wBZd+tDVN1tQKlT7lclOvj",
	"2k1G6c/3oWibST3Q+ZVTAh7bZERNkQAbXoBd+56doXn5mzDWrUS90qsj+dV7Y4UBwej9uYtmmPtu7IIO",
	"bi+zS8nmz9kGVLdJ39pQcbWTWOukifRpfm17VN7xbFv0nJ17pupv2nVWfqmu/s4U8q/Dn/XtuVc4Rsc6",
	"4WrDc9kmG6va4hGO/VlFm9srdQ8Q6EGAxzfXr9qHTyTTVHkd1BlEm8nixr2Q9az2Z000cjRcy9st5EI1",
	"p92RpXminfoKjRnN0qY0vrEK9JM1Wo4+EZnwM3nL6BuaAZIliOEQ9E464ESzlIqhHwSMUjEI5uaBW5Dw",
	"LTHEqhHCFDHjeK+e6u2ADzRT8ruGeWaSlDAERjDBMYYM0FAlxVYMLogRVMrCT4hRmz5+9/nTpwofoL5M",
	"Q5yYBjo9j6/N0/3dJx1whUSGox2OxFj+I3B4NwNDo0QFeYyzYpMJFcXC6pR7lcko7Z6cp6T4xbpK8PyZ",
	"ATOO2NzVolP1VuwX3M918vqthO1bMIS41GWt1yhKp26951qGnMaZQBdQTFQPNcNCTlZWMTH4nxOqZRcd",
	"Y3EpAfYzSKWg0dcqS7cTUmJesV3F5GINLU46cpP0q3htqiGRpi1eLCMUXZXeXK7HNii29xLd43lMoi6V",
	"QGfceWp/Lry1lHA58LVRW03Go6akpwuyui+GxhxIs/NLX8RvUJx8neeX/kWeJ1K2oRSGTcZTLXTltXxZ",
	"X0GE0pjOEpOZMbffBMmsDdO0XQzhQW+l/54jj+g0dzWNknO+dQ/edLTWPiivsyEWDDIczwAxD5HbN0d5",
	"xeqUx3O7xzkgY0we1MkYB0fBXmd/T3v56wfgjn4PEIHDWCKvBnlCueAKP+RfwZEdoRPSxJwnXazpULBj",
	"PmqTYXDB0Ag/qGdsjcoNh/CYZpJBPGgFRtiyD0wFR4e7+eIexxkXiPUu/HyZXi95JcyJ5bGLqi5zSViV",
	"PGd0c85+A9WPSTkcQ2W1VVNzPXLU8/M6AJBFiIEhGlGtZmOFCk2PWNqKXwysslKU6XSOM5jEgZ1Em94j",
	"xnCEeGeWqJc2ln0y3Ru6frv+i1YNj8XVbrKJEOmSVxlxX7pYdJnJjbrwXmjyq72+8vQVsrr1ThXU0ZFZ",
	"EaIa/6FA4egeMcdsP2VYCEQ2vgpZ/Sq0NxksnncAcy5JHfDomzzLxaGby7cmewRNJMqOhDEhSClKlnZA",
	"T6eW0I5nCPyWIeV2wWCCBGIc8CycAMiPwCDYkVi+I+iOtbH9Q9X+u6rt4znnXrf59n39G9Zi5NKoPvf2",
	"8uSrLeN0kaRDyis2aYsSbgQcL51cY/Vu5y9GEwGYtwZ9SY09jxfWfU5VHc2VFYAmsrl+baSQbyRWzVmE",
	"9VgNk6VbHR9lTdXXyBrd6Z7UxBvTf+jeV1tKb5qgEu/2l8CqDQTI+aB4c+F4VEilRVxPT+ZJ1/SXTPOj",
	"8Ooii+Mi6Du3Uwa90RkVF1opG7QawjfK2oRHbptHHfDTBBGlCpdl3XgKZ/yR1opo4DBXyZRQZN4BVE8J",
	"lVudyZJSoyTjIn9zTWWNas6cqccMWtXJqF6XdAiT65P3I39U+pKfTH9z19lPBQkVmo12/SkVcfj8RSnc",
	"Fmh7qUNPMhabgUUxJ5pjoSODnW1lM8bQpgdziUcHnD7AUMQz+2L7o/w0PJL1HpWP8CONEa6L5Fc79a0g",
	"LZ2e9XbGOYFqW8xkl6K98xZSyRSAoTHmgs064HqCeZ7LrXgTxWlIqHYaMe7AkozYzlqSz4wpGct/jQKJ",
	"soRbJVBBcrjr4LvVCyCY86T1HG6r6cFcrKP35mQecSV4w/ZvLfVPoa1cIHdpKDcQvBrf/D5afUVyaTdk",
	"SFmiqqR3/bXJNcGeAOcvy983LnHDgs59lv3Ipz7aBuytQL+auKyat4DSPLf4F7UWZUSsKbaXXFvMk5OF",
	"aG6EC+9KL7dnxbJ6O5ijMyyUhYu7+utagDxHzVV0FltbP3n+1sUBWPqs9lXyvm9PqbtLsqxQfgYTFJmX",
	"svRxKava5FQ9DKxhJmsM7JeRqVeUpR1P53pQel4mRZP8NRv90nMcg1RKXkoxXqTTVMznBN6jlqE1RjPG",
	"VQsNjHpljJm6+uL0eKwQQkWRP2pN16OishKhyuls/K+GS3gwJXly+Dm+gjqPkvKxn0JuprKCg2CEYrTO",
	"WDiOVTArUs9GLz/euJQTqe6k9VumrkvzUGApwsAR053UyLlnmX7IRjvagQuaZjF0Ao/1/dMBlwhGbUri",
	"2dJvgi/yPHOyzD0/WJjUoA9Vqn8TR3GHZtrmYCwXrgLBPsVE2RgS/EmnPAmhQGPK5M/HPKSp/spRjELx",
	"xOK2F6mWuz91/VryPN+81B3n20QnAAQKeRVy7U9nv7ckhzBQAQE7cuxBAPRGND3z6D5I7RmQAJrC3zJk",
	"F1UNi9XTEXm4mrZAPOJFMgrHMxESZ97rPhDj+O3VqdiVjhdHynlQe9AMNFEeBHlSb55nSeamegTuMTT5",
	"GCgDLE3alAuGrOLFBJfLzlIY3lW7I1TXaw+hxKUyFJgDeA9xbJNkWwWNVYiaDpdUyejZ90xb/evC9tC0",
	"ZBdQhBMnNi8XVOZmGay8oddAsEyiAO1dYF50cacJoyjIgwLUXwm9VxSrnAC6QES/50UX/HB1fgYuNKOV",
	"a8L9FmM/qDqYSgoIkRtU0KndqzSd59JQz2nnWfJ3GYxiJL6Os8EmnZ2S+/eQ8Y37kUzyxp14OLO/qjPF",
	"Ol3PV+d8vl1e73FprO1+6fGyHHtrDPNKfPRbmJqOZL2t1YpYNuCMCnM/QWJ01vLqUPUtb0PvEXOMxYWH",
	"CGfhDiYReuj8yje4MayI0I0RE5cmGUfanKGpPs9J+YWvSkCC8iuRffujAxrj5G0EvQrMsryfXAxHdIf3",
	"iKkbiBurQf7AsnGTUANjMu6AV+puP5ofH/+IPyoHvj9KHpUD3x9NHjUGvg8G0XfNse4pYiEiwms7u9b+",
	"oKZcrpqekY4PYHg8llKCbyU1h6p1QPdo7ZSZJSS4Mj35U4LYYZy9K02uzGreroWGJQg8bxLq0hp22VvV",
	"mwJfJW9ajo1ohKXouLGKM2JjHQ3KopWwibjl/LGcf4IJNB8SmKbG+/z44qZpq4/TzKcAaAUn6t0Ff6Om",
	"fCStoG8eVvC3a9anFPL+7ExnEnAVHZKHX/8Ga5jiWhfMvBmsE7fUsJDynmrU+iyJFHPTRPkzqMCSq2xF",
	"xWBp/7zs86oSYLJWB5wTY4bTX1PEgKUMiqfXNHU7GemLm8mXk15eh5iMe5Lx9cZh5xfJEIkpQiTPAaOa",
	"ysl8hbshz4jSdEHMUQW23P3xzHhpGtv4SqIOocKa4REZM46hajaheupI3UQRJY+sexvQFkFH1v+C+SBC",
	"b2TIVTYea3dU5WFn4AptMIWS9nV0WAvs6jeZBOBame7qXA72vTqXb0kotpqEgnMv67MM++jmYJPraIXq",
	"Bk2N/yXjLkhgOMEENQ41ncwqA8iNNnakgXpuMWNoENgX/1T8u6yvUQBzgJJUKEUfM8/+lmMWc0UH6AL9",
	"4DIIY8i0fsj6rHIbBB4hMMycJI7WXxdgsSAf3Lw0usXigXPlRXEEBsFVFoaI80EgBX9npl8cbXiKwjYk",
	"UbvxEcUlknmYiRsykWNAgXTLE0idU7urnqiR64aaLT0TPJ60YzlTndVbvWtTvNxQ0mbpN28UaDFV8WTK",
	"uJx/Htn3NG0nqkKESj8TKIkTgcRoikYM8YkuylZKgFefZdcCUi+6dCCul/aKOdQL81dCGwa0E6sXn5Rn",
	"Xq/QL62FD2pnderFC5PymSanKixhASLo2IVyAK7CCBtDarHABjm07F9tlhFjoYgxuVNF+g+nBMYYcrX9",
	"XNfQfzg15Mg41M+Q2REw0bnvgtzWoT7rlJLaP20IIwd1WsFq2OMszWk+r8ayyxzYepW3dupNRfMad83q",
	"1Ev6dr2aiuZ1e2WXtF50UixyvbBXLHu98LWzER4Ec7amXvoS+lsVSb09ay9vo4U4/pbCaAGGSwqwBH5z",
	"kQ0lBlOT3ZxQ0R7RTNHoIYzaHAlzoJFJcq7zz7jIvRYly6dwpSGofn5rIaoWnFHxygBYLXoJo6sc3mqh",
	"TdJe/d6386kVVJAxL1iWEjnPPNTUc7AgbJu8JFG99apGQ+8l2My72ZgylWyypLg8TxG5unpjrGEggijR",
	"17Vj69t9euhhcVCB3JvMtErWP2uk3bjf8lFSoTXDvFPfsZpqBqKlFsl4zljjcsFE5AvHMkIsL1BYe5+W",
	"BU3Y/rTbftG+/c6rhZQD+aHJn0SzUe6DgPNJ1DEuAoPgSUX97BQuZNvUsGV8Ku+muwOtEkY7q7g0H3eN",
	"E/QztQ6L1nH9LdV6ufrb9+CTeq3XGmsZN5K/QuBe96xrTMOge3na3Xl7fty97p2ftcBUcfryYzljp+SG",
	"MVHpJBigIYJEPxtsW+YuWSpjK2QCh1kMGeBYIBUigY0XP2QIttRRMgsPuspbC+6coek/P1B21wKnmaQG",
	"OxeQYauYyQhMhnic0YyDg3Y4gQyGKmLLzrWSowA8HgSv+9eDQO76zfWx2ezl8rXe1FJ5Vx2+R5hYA7ip",
	"pXOZZoJK0SjMk5ErPRWJfGnMBU5sqfUrU9OhmS/Jy3reRMeMktMHuY9W8cAFZOI1gyFyE/qurgq0jT+3",
	"AuHg5sod5Yhdk4tE4IV26SPz/iuFfldMZ/od7gvKxJyA2gnloi1oe6ySaqmnDIwCvAhdft/vAPUSCCKC",
	"zbRHlXOIzfkdqIBiOdyR6kz+ZaXeeslOyqigIY0HgXktehAc7h7uHh3u2kbm544IU3Nocn1n5Z3H2++O",
	"9D+Pdx6LMP2vLEr/i4cifbLuu4x/MsvvMubZqkbmfR9MKbtT/KX1NTGeUq9UxuJjEZt3XlT66/d9EElq",
	"otwybMRChGJ8r9J8Oe6tTqjTTh72oLO8aKdurws/eEWZLc+fzjXpWrQbiXHV0yESxpf6PWYCyP9kMO5r",
	"HRP40O2/1XZcon0lExV97Xe0W+TZWDsY/brLpaaoxidzWRu17id13KWL4A8VqWduCNW5JrvlKPNgB4lw",
	"R4X370hwOtERo+smU/+scgLoFxQUHKGaOkogjoOjQCCY/IebyDqw7mSKf9EIA0zGTHCNYCLlCSabWtVV",
	"qXXNKe6Xche3j33Nnhjlr0nYprKNozCGTJv6HdcmOgKjGCGhVG8oGltfdO1qJyYIsxz7uX6KKMYhIhw5",
	"Obe7KQwnCOx3dmuTmU6nHaiKO5SNd0xbvvO2d3x6dnXa3u/sdiYiifWlI9R2VRape9ELWsF9nibcZgbX",
	"D61IPAyOgoPObmevyLrwe7Dj5CszGQCtLlrnVPDlOD/WYSEQHBeNr3TjIul5YZ/K1ZS9KG/c2DLQ6IW4",
	"eEmjWSUfmHPOd341mmFNyNbjERqB+FxGcxOmoF+k4voU7u/u/aHQ+bYkkrv9dHf3ywKW52auQfESRiAH",
	"UkKy90dBckNgJibKrdUsysEfBcoryoY4ihDRcLz4o+Aov/qmgNn/w4C5phT0IZlZdFH5Fp/9cZt0pe+A",
	"G5IbdjSfBsdKOdVIJYNbWW0OFd35XVL/zyoQCwmfhxqMtDiVR/Y0Hvw6MX2NxDxKWqTs8OQOqDpqLybm",
	"QFAw1jZXLHsw+c7M9WbCd8pUs+VsV1UJmBH8W4Z6msfW4US3NSK7+ycisuc/fqNqDVTt6R8FR672/UbP",
	"tkjPDHdriNeOTb7cSMVeI2EyGJkszSbTcTMb+BoJm/dZJ4VelVzpVoYklQfnVd+p7VCsz/XsJPlb40rz",
	"n0PwvkhMooZVKZGKcb1Zr+eN+9XJotmSRhq4rw989SgCJ979T0Um/0jyBAr69Mcxf39ets+hSppo+ElQ",
	"4RGTQhH6A8VtELiTRfxkER1SzUpp6dejQy6PpCDcFs25XUUgbquhv9vCHpYiqZYSh/9gkvRN7P3GIC6m",
	"wN84xAqHCJpYxJwYt4I087B8N+Zh21UJ7qWORdwyyS2emv3qNHeLdO0bif0rkthvpG15rq548WZ5MwMB",
	"vkdV59sXfM+gfrUjXR/8z2BPaIDqmx3hmx3hX0SU/FPzUzXK10gRF5kMXqu3F1ciiq+R8FHElbiu5vG2",
	"ahf4A7RdS1HGb8r/b7LdvzQt+qxf07DEQDuo7MAU79zv6USkunUtFZGlNBxQUpXNlIuRIQSGEaxr0cs9",
	"NNMZt7P6FD7ffv7/AQAA///ZzdXtlgcBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
