// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3Lbtrbor+DynJkku5L8SlLHd/bso9hOojayHT/Sk1a+OxAJSahJgAVAy0pPZs4/",
	"3PuF50vu4EWCJKh30nZP9p5pLOK9sLCw3vg9CGmSUoKI4MHR7wEPJyiB6s+QMvTP+70hEnDvnzRFBKb4",
	"n90hp3Em0AUUE1kpQjxkOBWYkuAouEQpQ1z2BSAB0NQFIxwjkEIx6QStIGU0RUxgpAZJvf1cT1DRWlYB",
	"ggKo+6EEiAkCfMYFSjrgjAoExAQKAMkMoAfMBSZjXXWK4xgMEaD3iE0ZFgIROQP0AJM0RsFRsHMP2U5M",
	"xzswTTsxHQetQMxSWcIFw2QcfP6cf6HDX1Eogs+tBsCk+D1iXM2/upzuRc+UgQiNMEFcLeFef0MR0FAH",
	"dATEBHPALBih7EB+hgTo8TvgCjHZEPAJzeIIhJTcIyYAQyEdE/wp741LmMlhYigQFwATgRiBMbiHcYZa",
	"AJIIJHAGGJL9gow4PagqvAP6lCGAyYgegYkQKT/a2Rlj0bk75B1Md0KaJBnBYrYTUiIYHmaCMr4ToXsU",
	"73A8bkMWTrBAocgY2oEpbqvJErko3kmif2OI04yFiKtdIVkSHP0SGMAGrWAU4/FEhCKWgxWfg9vqLrWC",
	"h7Zs3r6HjMBEYtYvQbEh7/OmxbdXtu8e9RWfJqmYyYEe2mParuBEIwak16qiD5tlF3p/EYBpGuNQ7a27",
	"cHUQOQpawW8ZjGIkAjkQERATxIJWMEFxErSC+2RpAKj5HOfdmg/v8t7zGsUg5tMbPZb59T4Jbues2i5G",
	"9oOIkACAcXw+Co5++T34d4ZGwVHwbzsFndkxCLrj7fAVjpHt6XNrjQ4uUQwFvtckSvbA0G8ZZiiSQFH0",
	"5rZ2qJdZ3gnispcrAYVnk00piPEIhbMwRoDLimBEmaKF/j1nGSF6A7mgaYqi5ffWN63LvLuGCld2lCXW",
	"e0ru30OmqXSJZqOiAEYRlnVhfFGqUjsxZWCdknvMKEkQEeAeMgyHMQJ3aNZWhAekEDPeApjIzUERiDLZ",
	"DWAZEThBHSAP1B2aKRKmWyAYTkCScSHJ/RCJKUIE7KkK+88OQDiBDIYCMUVpKnu/AonPYXNBmajjgPwK",
	"EpimcraYyL1PoACDYEK5kIVH+XmWvwYBeIw6404LDILD3cPdo8PdQfCkfEOZ7/LehEIS8OAo+D+DQfTd",
	"kfzPv9cvrCXmzug9jhB7CbkHj49pklACih3XGBzHLgorcsbrtzkkhOpLaxPs6LIhFgyyGUiQgBEUEDgd",
	"d8ANR1F+ncUzMJwpsqouIRqDNIYEWciW7pApZXcxhZEi6E/AdIIIEAwSLjdK7lltiQDKm5VEiAGFekEr",
	"YAhG5ySeBUeCZciDO7C4B1amXfYO0TApkZsNSGoTEft821qBiinWxIFQC0AOEsoV74GIiGeAI2F3Q9Kz",
	"HS4gEyBC9zhEoHvR4x1wiWDUpiSeHYFQ7ao8sbJdhBkKhd5OOcrsfwNZDRhWSJ4n2a/eDRSV9oqnKAQR",
	"ivG9KjKMDxwjIupb9rkVSDrawHU6vcpaOVHZ+5///r9lUgJiSsYtoNc4xWICIIiRPKSAMkCyZIiYZrPM",
	"qQeEgqlkiHgKQ9TxnV2GVHevEUEMCi8zeUwzifoAk5AhSUFRZGFuWjsA14RRom6V8wCKz1T1UfRn2JYc",
	"GvJkjxFThNm9uu25ul2HXhuad5WiUIEUS5AmmEBBmfxgqLaWezTD1HDCDD/ldF7i0xpbmQrldoqna2gi",
	"ebBybcsXNjQwjF25zX1j/+9LvX/OafnsTJ2OHN6fWwElaF3a4wHXWlydZ3Fr9ePdiLV6qu7PWp1UNmEZ",
	"vuzSSE1vcYK10F4VwnU5iFUFQ7trYkf55g7TzENqLm50J/KUy2nxDnileRpJOhhW3NkQyvuYktrtWeZk",
	"djvfP/ORvAQllM3qg/fVdzO+Iq801cwEkELnBjPZf/Y82UjSr23FvF0IKeGCQUyW3Yo439dNLvoKlqy1",
	"PMklZNwv1OoypZsAHJNxXL5djJZG30SuxHPBUAqNYHMlbx/9ZyG5nDJGpSR6Q+4InUoSJklIjASKVBMt",
	"wJi/ZJOVJSY9dXcitUJnZrUyr5Cli+zcawXFYmpF7uo887DL9Rep9S+xkzccsbogxzLS5X4+KONIwc7q",
	"LLS6TX2uMYJWFTVEUkQDmeQEpJCGuWQyJC+hepC9Qa35Ut3IM42JUtvl1yf36EjAYzyyv4cxetIBJ2gE",
	"s1jkGi4zKygK/kLOhMvhHo8VLyXlBEapeALwSE1J8iZ4hFFU58PKWp8bAwn3c5vf4bRt6VE7pUoaMezl",
	"OiftPY2zpMLmVzlzrTiEii2NwL1qIZeu2L+6iqG81X6O94bg3zIE3I12+zU75KFYHsY1jCFOLmiMw9mm",
	"tEtD47LUZZUbVAvysIK/b8Ks9BI4Rnr0Ese41tXel4z6tjpTM2vs8XYpxsHTskYS9PZ7iMJbzIWi9s7B",
	"NJUlQmCBEr6dfQ+KAwQZg7NggxN1WUXLSJMOdUFLkhO0Gs7ZhE4dajKBJIrV6TPnQ+sOJgjQKalqDpRk",
	"ldB7TVvsxWfGu11DY6PXosn+/Jt4K1ThrEYOGo78CDFEQuRjfkyRpdARSmM6QxE4P+61JWbEGErhUWK1",
	"lJblbTuCoQBDGN5JeM4d20cK3PmsIyHyqyxJIJstyfOU9WG8md95g2AsJrOgFZygMYORuszrPM4Zdeey",
	"Ok9Tnn4xaGMVZzaNdTzsTLmCl60pV6kurGkrjqGAMR33BEou0WiO6F6RW0rN1iJA5ZE1Qa1gWGWUpfHL",
	"03WjWnQEY45qqlDA3KMEgZkJkPS2BWBMyVgLR1LSCykZ4XHGmmQ83dbP8NmOFS+Q81JyGEnPUsgk9ffS",
	"gXACCUGxx+xJHJEtjaBAwNQF0wkOJ7l9VpErQUGqtzqvnCGuCS28hziWzJ93AnKS/kW5jI0LOQktFPuX",
	"c99oxQX3MMaRNdtqIIUZY1r3qUzP3OrD3NEWUzC7M2YtxSSWxzS5zSN5ZNAVHssr6RL9liHusVI0Vi3s",
	"zvKiY+ajUv8DjscERSAs2oIRo4la63HXYwkomcPXYAry5p9bwR0mUX0dP2ISSdyEQEPVmILyRdhr5PL0",
	"6hpYU7MWXjQwnfUWZvUEzgAmIyvm5ItEJFJsvt7dGEuugGdDpWExoJLySAcc5+pTjcZRB/QIOIYJio8h",
	"R1/cqK7sFm0JMt7x61u0TWWtfTlXgOsjAWVX3BC01UluEwoaBjngOa+zxb51n3W1co5qBtMcGJk1bn4M",
	"c8VzCYV/YjBNkWR/aEYiAJUk2w4ZkngDjq8uWyChEYq1VusuGyJGkEAcYKrwBaa44xxJ3rnf68ydQv2g",
	"oocU6wvjCoWURF5VlmqvDbG5S4oihljMcqWWMxE5jDZ+an3+wX5QV++3AvQgGJxnKMylihoWlwWEmn1Z",
	"dgyg0OcH5VqFQlFgYazol4RzStMsho4xpXvRA1wRBQl7VV+uHEqikySZqFxHBWKwJsIrb6Qh5Oj50zYi",
	"IY1QBC5O+8XfPx5f/dverpxOB/ShCCfGT0iiYCcnxxjFkbxloIsP82i6JnylLRnOBPLRBkXl2ZlXKuiR",
	"SCOZsfdYnNBttKFLUePfMhgrzYq6fuW4CSZvERmLSXC05xk1wx7qftM7+Qq75kyCw7FP7r1R33N1kbpu",
	"kJKE79AM6FYONMz1jznPytdlSUheiM5W/TZfOPsKgKkQS4vbJVTZAnVsEG0LnIOpZA5hvBMhgmG8M4I4",
	"zpg2T2f5+VZLdyyuvGEzAB4V7oIePwanqv8Ymy7rXFGrgCagkmvPN2KpAygpMM79J6qGX1umRc/Comp2",
	"pQN+lNIYCJ2KDIGuAh2KWuAEESz/lRB6BXGsJ7W+6iafkVdlU2Jwi3Utjy11y+HW3CBKPjBrKeQ8jlKb",
	"9tOgK9xUn9kkS69nPl1KTF9PxUliTJpne/t5BcyxeLkZwuT95GiSevyYNulYG9grh0X4vRxqzjp5LwW5",
	"i5CAONaGRkoQgPLeErkIrIVV49NjvY3lzXCZcwkLYep3G5NfC8IjJbJMSShgROOYTqUs9mPBrsghXbEF",
	"3HBkXGjkbilVRyT5YXPthtp/FpEs8dhLIRfXDBKuIYqbXHtkvcIVppiryNuiSMt7EnLmYpEzIVRMECvR",
	"bynYtWVffgmLS7agPos3WQIJYAhG6n4w9QDWt5yEkd0/OKSZMDPOp+flW+hQ3erRPJchufqOlWk647xm",
	"oecpoDGFXLtxKVt6luphXWb++VMvM88Q5H61yeMhw2j0BOgahbxgx3zEl1rpJjKhHapBBjRdt3y4lK+s",
	"2NjVCdFi3X0JIi2FgnQErlmGWuCVUg0Co211tcuyPGgFqoKjT15OfVyZnemr8tV2Xfmcj7Rw6Q0+8cYf",
	"vkA87CpJnCVa9iVoBdcX/feIKdlCq5xtgWZsFCAkV1OvGoaIczyMUfWHJXwXkHHtVjAjofrjvZRvZQ1J",
	"wDLRk9fRmCEu0eQmjaBxD5CXk63az2KB0xidTwliXM3rHofoBIU0STDnmBrHgVcxQuIExQK6Xgi2dunz",
	"clt5ShiN4wQRYThqBzi1sjJsGplyp4vGOjngG2vkO9JYozydS5RSjgVlM+8+ye1pLKhtpluYb6wCvt0y",
	"9cO3xXoznI3WH9zt1l++yKbPOVUjPK6aRDbgEF9j4elzLf6tuN+vUMiQ2BZHuK35vREi9fU1D9h1V8F/",
	"bRFE+Ql9k2Nc3Kgy/SllPq9LN/Zjex4RKs7Eox9iruPhNtwEvR6Cy/M5aWY76lMiqXdu68zPShmKia62",
	"OGCuMNxQYBotVlO5vXt9hNYIKqsvbw7lYJScPqTyKvH78DNKAMor2EAhyRnLWURZrIxXOEG8MyASHKYG",
	"5uDj34D5/8cj0AZ9TDKB+BH4+LePIDFa4932sxcd0AZvaMZqRfsHsugEziR4+5SISbnGXvtgT9bwFu3t",
	"O41/Quiu2vvzzoBcZak8JSgCcsuhoHISbVnxKFdsQzIzBjsTqSO7wQRM5JTz/tA9YjP17Ykc92P74xG4",
	"hGRctNptH35UgNvbB92+xJJD0O3r2q2PR0D5LdnKe629fVObC6UG29sXE5AoGOo2Ox+PwJVAaTGtHdtG",
	"T6ba4ko7v5bXcliARDL2h06TATnVnsgScmC3fdjae97ePzBb2lk6ous444Immn3okRGdZ0epSmTKzKRD",
	"kSMQqo5sxJfZFe88qppxpxNMNIYqnbISXsvuMMvREcUGFZJsITWt4DJxATEDIc2svzUEqeKrkIrIU+Fg",
	"HXCBWDuVFdMJ5Eh7bFmUJaAyDcsVSgRQtuJC8WIkQg5CyNis8HMNrVPvjqACxmY+HkVz7vxbV/SrACJ5",
	"zH6lCsSO3K4CJE3UO0MAxgzBaAYEYgkmMF5SYpfC7o22UXtoMC7sDEo6ry5pyrAbGGaAvLyWRPUyb9mZ",
	"dk6tLVuZWBpGbFpsTR1d+Fzredwuj6IpIhEi4UwKFJqfvESjtVB1bl+uN0YpwmqEyRixlGFSOGcoEqTd",
	"f6wXDXvEAXowMf9RPpIPB12e+KwxNK7kTFMeStM9VTLGAlAG3lxfX9ha5gKX7Z946YqzIv/Q7pLNDHJw",
	"hDpW3ExBDq8ELwGu3nRbgE/g/rPnspGa0ZBGsxb48ZADrmSUXPFpXAD883MOSlcso1x05xtO5H0Vgce4",
	"gzrWGdJsRj75KeTWXeTJskeobmKpbuOaSL0FXPajMJ+RcMIowZ/0eXbApGl1HV8xMp6t+ippgRCmIlOB",
	"hrXIXB9aX6KRj1lHrK3L2zkKu3smOQO1o8YTTY7QUmrR3O/XxFjqKWzI8M+nKeu7Q2vmYOWNNAtzfMHS",
	"yYzjUO1L7t9qw6nKvl5NSTu0C5fpPCh7IcVwiGIFuVGMVHij9dLOQ3WD0fP9aDR8OnoW7YfRcPji4ODF",
	"wfP94bPR3uFoP0T7zw+j7589f/piGIWHu7u7B6NdtPt0/8U+/B6NDsMDBbRvHmrfPNSWP5JW27eh6cF0",
	"tIbv2e1qx7wWIFZ3lt5SZgKUDFEU+ZjGnyZITBDzxZrbRtZDZkipCHUAgIMEQ0pjBIm9dBUjvgHYVXsJ",
	"mFlBS/1uNRXTnMvrLA59gtGsgWXKmVknwk37Pku+XXPtS0dYqWB9Po9ltnWAtQo2RZx6zHdbigWUolSm",
	"QmJMHGBvBIYxJHctbwaCjNiYQCU3qT7NBx15U43f23q43kan2x8s+7nVHEdVWPxMlTxYpwrKLYdVzeEm",
	"vME0EqkdrGsVRtL8/LdWz8lQo1XlaBGfsoLrChb7Jiq2pRKK5gnAKZM+bDQkc0+9q8TQlnh7QytmsBRV",
	"/sVs1fNjkhos1yvC/ximcIhjnF8My7OHbtNCaWKcDA1TnGf4KO8B5X0arXf7nKumOQRWWqtip5vQ69hx",
	"iSkM8WYdWkSoL8TKno0J/y6tcGpjRZr6XeRtWR7nduWVcxp7c5U5xVUhLTSfQ0oICo1pPj8XdWBwrcPu",
	"nfgvD1MMeieu40dlBP8Z0i37DjdYIQ051uaj5AmjzKUq5218df9eyi0WQuJGHmGCBYYx/qTl9zxbn1Go",
	"tfI5C2qbtQASYdMelhPblA5sZVUtB4Ar7q9rYvblz7C5s5Q61krQICobpnPn0drGCsjGSGzEfRUjXavO",
	"/O5uepwNFu90Xr9vc8dtfQB1fqsqEBIkJjQqH1PXCeWGIOVFoVxMQkHZ7BLx0qTneWfMm7HT87xq5VEX",
	"gabC9a5G4S8Rz+Jcz+Yk+AKR7FhngQJQCJSkolAAW1WJmnIdm0YwjocwvLtscBO7cpUr7qCm33w8FMcq",
	"SlgLvtBMSueHzeLYxBSnWRx3QHeoc1SNAKGm4hRy2xeKgKFIuohnYYhQJOXh4xhBiSf5jAh6qE/FLl2v",
	"WWcC84u0HH/y4ObpQ2oSHOrxJfnBBPROj1WKGw4e/4hftkBf/ue1/A9l4Bq/fJIvLJ+ebqqTbcyQALmj",
	"2LpJbqxdSaAxw2J2PEHhXdMd2ly3pgAs3bLYtgChbAJSxCS91jaYNZm5tpeZKyxS1TH1jLbNwzVDZItM",
	"XGP3C7wMVwB7Qf5snPcN4da467rb5Q5cqxBE3wKKkebVcefQXC+fXXOVYt5LwrrRkdMIKU0YXrtZ0oqB",
	"Vo0SISKwmG0Z51SM9KryT3FklOxTrGSB5CNr51D1WhW5gElaMi0Wnd+rloX8u5wpcXsn1aRW0ptpZXmR",
	"Jlvfke1SgPq0l6YBjSyP45OZHyQ/HVjrzFfOX8tf3nSEFxCLOp1YcL7f2nyna8mJebbULegdqs4TlVSs",
	"X+quqgBgi9eUr+cm7HSzpPtgW7+PtHOzQZGqx637ZUU8rcy6immV4tIsPOW+qS2othhnz3ndyW49z8pz",
	"5suBUvN8VFyqalDfwHOb6GOCiThS6SNKeUuM6GDT/NTyNT/irqMHQyFlEbeRMUjZvIbIyQIne2Uque1H",
	"xfB/tHYwzA3mPOJ5vJO2MlimOaJIM8o4kYJMLhmYBB7/89//z8U/TKwtWsQzEGEeUmWFCyGJsBIHykvj",
	"xhFBfeUgzYYx5hOTjsn4WinfDDol4Lj3BDA0hiyKEed5RJaK8dZhmlJs4lreKUQcKdzoLLxKsiGK9c94",
	"cwjvokiyU6zMNk681flxz0hS+UYq8QPOS0hTSY2iVSwMcRrfazULJOWOO8FCFF+HHp9feQixH2/flxV0",
	"51c1k5STZ0aWnOBxY3B/pMqqfRmE0J4oR3C30+k0u5ls3+JVIeIaDuXFrEjR86iKlfYmd1lexAubVLRr",
	"AqA8uTyZOuZ3W++0yFy7xW6rXj1pFuQjmXVstF3zPa55yeVab2D5eZYitdhPkJnL7JhhgUMYezKbrXLn",
	"lifqJk6rlxaD+0qdCfmK7SR9ZQsD2xzPgAZNyJVOey4LhiphRBOmuwas5TIuWm+lLUYYlEMpapEG2lbR",
	"PLuKJyDfOKNAPdbHNydOY9Rgro4t3EKB7wtrg1Gzb+yq5VpWvIloyqzedtTnKtJ3kxkbZrEaOlJ9eINp",
	"x/6cAphAinJmuQ1BWAml8AFRexhEKyqur3PfhEilOsHysimHjVSCUKAIJxf6XRWv6dmikqoIzAss5eXX",
	"rNXaF9fOIyNYKG+SlslhrvMeSxmPZ6MRfjBcFZ+gOG5zMYsRGMd0aAdT81ejwzHEhLsZ52IKI6SHUHNK",
	"4INNs7P/7HnpxZhfdtsvYPtTt/3z0WDQ/mdnoP73y2Bw+78Gg/Zg8LfB4B+33z3+j+XqPfnH48Gg84uu",
	"6Cv2vkuz2IlR69c3yCHsBG2abvJ0jqvcmGs6wBZNXb23X7jnTtJWcz0A01bKOoJBHGsvmFBkMC5SNmx6",
	"m1gTvZu+27nmN6WMdS80z/GGdReH7QxZcSaRu1zxdFiX4LvdLJ+nJ0cDnSpYOWVZfxW5ld6kHO4Of5Hc",
	"PO6lvv4FWDhVqFuvFDGzZs++4B/VuesevQUPa1ctbjSG21MeW0nuCiGyTKyAOZA67wYi+ftJ+gIDj8/O",
	"r0+PbMSLCdEylj6GRMZIKcfXstEDxjvuV05JG48JZSh3h8s1bttTJ26Dfck72iz21SvCSpZjYzpUoz2a",
	"B7Cxeev2WnRSZoz85L3Ed2yHsOsZRDcEi2aSnhVxZBvd2lGD2sIhuCXAli+TwH+3uDjjnvmcECrsLBZR",
	"YIN7GlYUu9f3a3SowgSyaKpC/IgNpsVkbD1wS++nbt/f0czBZkL6Yh6PHnht0f6wUl53vynsXOWh8Kdw",
	"v0RDSk2KkAs6RQxF56NRyVbWnUIsVL4T4/Gm0+mMYhyKC5jxFU0TpQU5U6uVObP1lJaVIKUid02e4tIy",
	"PeVVY0mp0AcMT7UqfBbscYnSLhcFnVsszGFyssWih5Ty4lrV7qwDcgrDicr6GVLGEE8pibhRglvxWJ8q",
	"E8SW856zzoAsjqfWiygdypDGsfYQyqN8Grl/OclGh1TJdnSVP71R0XvPsBu409CHU6PB+9fbs8Qnn4fo",
	"S0oF6J2s2lXYuFCrz3c7/KhjTdpts/aPZf8pE4libEKECxjHhWuYNWmENEm0QQbHfhustu2sfd3X4vkt",
	"W30a47FKdjQn3Ca3eimrS0gJzxKkbC3aDtVRmcScV0tC3NZ2qyEm8hLS8dQSKB2dbkzXxcIApgPOEyyE",
	"dYmDBNA4QswEaeQmNQ12EwOL4sgf2kNDrJj91XaxmHPTThY1Nt/N/LLVx9J/HM7zG/nK3shL4nE1EMw9",
	"eflxqc+iVT7nK16FNcXIAm/ZVNVUfo4JJHCsMxQqNNOsknqkOYyzSJaoLTDfnSfBIjolRlMlIW5S13pc",
	"oEy9K50AZT3pQ68w7yJnTLfa6ed1oB6tZcnUs9+qW4nL2lmf3S/M2pUgsEXWrt7vCo4lBWhzr5L0mp5A",
	"lZj5PBPnI/O3kwNuHatWaZLOEJ5Sd1Rv40oyunLpQsMV5ncLszRtJzFS60+W7slL5Iz2U1E33YGib5jf",
	"6bTu9VOXQjFpsvwzpBz0gazjTF51X+5z/lrUGJ7kv427ms3L+prAB5xkSfFwA4xjOnXjQnWEj6B5fhf9",
	"vH7eoCDk+YuJAKqcAFSSjHvjS4iYyfRrPV2Ufks/1Fqkg8o/qszkR+Aj15mVuH56ogU+JvqDTpYkP0z0",
	"B5UWqlN+Bv/xP45+2Wu/uB0Mor89+cdgEP3Ck8nt8m/in5KQyptrmcARZOpqRFVhQ2pnoYCFljd3W7UU",
	"JY31E3P61Yelc3nqoS5MY/v7pemkeTmVPJ+egINqlTlP/piE+xI1dIRKSTG9XvqH+hTL0f4m2cPeQfT8",
	"YD86fH7w/UEIIYrg86cRfLr7bH/04tn3Iwi/f7o/Cr/ffba7u//8+6eHw/D7F7vPn4WHh3svor3hrhv5",
	"H3IWHAVt+b+Xp697Z+D49PK696p33L0+BZen725Or65V6YD0e72XL389fsne9V52T16+7d/cTS+nH07e",
	"v3t3crrbfejvv9vvf/rh7vzkw6ezT2e/fvjpVfzz69P9s9eXk7OT7t6A9JMPz86uo+TDT6cHZyc/JB8+",
	"hdOz6+60/+uHg7OTCf7wKXzWP/mw9+HT+Gn/Or7r/9Sb9l/dTU+nH978SH/uDcinX3ePu+8+9OSvT7/u",
	"nnTfhSfvxt3TNy/7xwe7Z5c/XP9wcPbTeYzwiw8/3b3s7/Q/0bOT17P+5Y/Zp9PdnQEJf7yb/ef7H9DD",
	"m992H3pkf//D8dnZwc8nZw8P05+ev43fjQ/wr6/J/ZV4dz583u32u/T18fFvr6/6T1+87PaPB6S7O+72",
	"T2+Oe+9OrtgDfn7HouMfw7fHk6j/8mD6fe+35CT+eXJ5+nr4pn98evWePOf8otsb//z2u3fsBzEdkMPL",
	"79jTFMMP9z/fCcbvDmbHvezTwaT3fUw/JP95cRAd/n1AFNhPz07mbMm3vB3f8nas1E2NwmwhhUe9z6/w",
	"klRDRmdfyrTGqsW7AH5RIKfxjtXREPtEvaHcFBoKbWroOS+2TJ1cIPZimUAOhggRYDtoSv1hEwI1qfIW",
	"qNLeqg7k1aXe6imFNYGe5DLTGIbIVJOHUak8Hpu8Q09aQE9BZelIEBubx5C1usPmjIpsLeco12DnHU6F",
	"BbtjKIYC2gBszYiBEdahzQIoC516ZtY3fsMrVM6YpZdv/WH92hm72LY6ACizC1EPgZlXbxUCqVV+WRiu",
	"CjKla/COpFJBKpOnF/1qh9qg+uYn13ErWV/eaqYLdUFnwUwWkQfHR2VTQtGUNk8JBFCYnDguqVBxug6V",
	"WC4SzLZ4OVucw9DUXUK+dHptuUta4o2WRVuwhqOQB/DFQVweK/0KQG81zQs5FfV0anUfuaHQPrWVYsZ9",
	"++J7B899r4vrFwNcRPNcAWXfrQ1TdbUCpU+5XJTr49pNRunP96Fom0k90PmVUwIe22RETZEAG16AXftI",
	"naF5+UMv1q1EPb2rI/nVI2KFAcHo/bmLZpj7buyCDm4vs0vJ5s/ZBlS3Sd/aUHG1k1jrpIn0aX5te1Te",
	"8Wxb9Eade6bqD9V1Vn5+rv54FPLD4c/6oNwrHKNjnXC14Q1sk41VbfEIx/6sos3tlboHCPQgwOOb61ft",
	"wyeSaao8+ekMos1kceNeyHpW+7MmGjkaruXtFhJQzWl3ZGmeaKcOoTGjWdqUxjdWgX6yRsvRJyITfiZv",
	"GX1DM0CyBDEcgt5JB5xollIx9IOAUSoGwdw8cAsSviWGWDXOMEXMON6r93c74APNlPyu5zwzSUoYAiOY",
	"4BhDBmiokmIrBhfECCpl4SfEqM0Jv/v86VOFD1BfpiFOTAOdnsfX5un+7pMOuEIiw9EOR2Is/xE4vJuB",
	"oVGigjzGWbHJhIoCsDrlXmUxSrsn1ykpfgFXOT1/ZsCMIzYXWnSqHoD9gvu5Tl6/lbB9C4YQl7qs9cRE",
	"6dSt9wbLkNM4E+gCionqoWZYyMnKKiYG/xtBteyiYywu5YT9DFIpaPS1ytLthJSYp2lXMblYQ4uTjtwk",
	"/SqekGpIpGmLF8sIRVelh5TrsQ2K7b1E93gek6hL5aQz7ryfP3e+tZRw+eRro7aajEdNSU8XZHVfPBtz",
	"IM3OL30Rv0Fx8nXeVPoXeXNI2YZSGDYZT7XQldfyZX0FEUpjOktMZsbcfhMkszZM03YxhAe9lf57jjyi",
	"09zVNErO+dY9eNPRWvugvM6GWDDIcDwDxLwubh8S5RWrUx7P7R7ngIwxeVAnYxwcBXud/T3t5a9fdTv6",
	"PUAEDmOJvHrKE8oFV/gh/wqO7AidkCbmPOliTYeCHfNRmwyDC4ZG+EG9TWtUbjiExzSTDOJBKzDCln01",
	"Kjg63M2BexxnXCDWu/DzZRpe8kqYE8tjgaouc0lYlTxndHPOfgPVj0k5HENltVVLcz1y1JvyOgCQRYiB",
	"IRpRrWZjhQpNj1jail/MXGWlKNPpHGcwiQO7iDa9R4zhCPHOLFEvbSz7Dro3dP12/WeqGl6Aq91kEyHS",
	"Ja8y4r50segykxt14b3Q5Fd7feXpK2R1650qqKMjsyJENf5DTYWje8Qcs/2UYSEQ2fgqZPWr0N5ksHje",
	"Acy5JHXAo2/xLBeHbi7fmuwRNJEoOxLGhCClKFnaAT2dWkI7niHwW4aU2wWDCRKIccCzcAIgPwKDYEdi",
	"+Y6gO9bG9g9V+++qto/nnHvd5tv39W9Yi5FLo/rc28uTr7aM00WSDimv2KQtSrgRcLx0co3Vu50PjCYC",
	"MA8GfUmNPS8S1n1OVR3NlRUTTWRz/dpIId9IrJoDhPVYDZOlWx0fZU3V18ga3eme1MIb03/o3lcDpTdN",
	"UIl3+0tg1QYC5PypeHPheFRIJSCupyfzpGv6S6b5UXh1kcVxEfSd2ymD3uiMigutlA1aDeEbZW3CI7fN",
	"ow74aYKIUoXLsm48hTP+SGtF9OQwV8mUUGQe91NPCZVbncmSUqMk4yJ/c01ljWrOnKnHDFrVxahel3QI",
	"k/DJ+5E/Kn3JT6a/uXD2U0FChWajXX9KRRw+f1EKtwXaXurQk4zFZmBRzInmWOjIYGdb2YwxtOnBXOLR",
	"AacPMBTxzD7D/ig/DY9kvUflI/xIY4TrIvnVTn0rSEunZ72dcU6g2haz2KVo7zxAKpkCMDTGXLBZB1xP",
	"MM9zuRVvojgNCdVOI8YdWJIR21lL8pkxJWP5r1EgUZZwqwQqSA53HXy3egEEc96pnsNtNb2Ci3X03pzM",
	"I64Eb9j+raX+KbSVC+QuPcsNBK/Gh7yPVodILu2GDClLVJX0rg+bXBPsCXD+svx9I4gbADr3rfUjn/po",
	"G3NvBfrVxGXVvMUszXOLf1FrUUbEmmJ7ybXFPDlZiOZGuPBCerk9K8Dq7WCOzrBQFi7u6q9rAfIcNVfR",
	"WWxt/eT5WxcHYOmz2lfJ+769j+6CZFmh/AwmKDIvZenjUla1yaV6GFjDTNYY2C8jU68oSzuezvWg9LxM",
	"iib5azb6pec4BqmUvJRivEinqZjPCbxHLUNrjGaMqxZ6MuqVMWbq6ovT47FCCBVF/qg1XY+KykqEKqez",
	"8T8FLueDKcmTw8/xFdR5lJSP/RRys5QVHAQjFKN1xsJxrIJZkXo2evnxxqWcSHUnrd8ydV2ahwJLEQaO",
	"mO6kRs49y/RDNtrRDlzQNIuhE3is758OuEQwalMSz5Z+E3yR55mTZe75wcKkBn2oUv2bOIo7NNM2B2O5",
	"cBUI9ikmysaQ4E865UkIBRpTJn8+5iFN9VeOYhSKJxa3vUi13P2p69eS5/nWpe443yY6ASBQyKuQa386",
	"+70lOYSBCgjYkWMPAqA3oumZR/dBas+ABNAU/pYhC1Q1LFZPR+ThatoC8YgXySgcz0RInHWv+0CM47dX",
	"p2JXOl4cKedB7UEz0ER5EORJvXmeJZmb6hG4x9DkY6AMsDRpUy4YsooXE1wuO0theFftjlBdrz2EEpfK",
	"s8AcwHuIY5sk2yporELUdLikSkavvmfa6l8XtocmkF1AEU6c2LxcUJmbZbDyhl4DwTKJArR3gXnRxV0m",
	"jKIgDwpQfyX0XlGscgLoAhH9nhdd8MPV+Rm40IxWrgn3W4z9U9XBVFJAiNyggk7tXqXpPJeGek47D8jf",
	"ZTCKkfg6zgabdHZK7t9DxjfuRzLJG3fi4cz+qs4U63Q9X53z+XZ5vcelsbb7pcfLcuytMcwr8dFvYWo6",
	"kvW2Viti2YAzKsz9BInRWcurQ9W3vA29R8wxFhceIpyFO5hE6KHzK9/gxrAiQjdGTFyaZBxpc4am+jon",
	"5Re+KgEJyq9E9u2PDmiMk7cR9Cowy/J+EhiO6A7vEVM3EDdWg/yBZeMmoQbGZNwBr9TdfjQ/Pv4Rf1QO",
	"fH+UPCoHvj+aPGoMfB8Mou+aY91TxEJEhNd2dq39QU25hJpekY4PYHg8llKCD5KaQ9U6oHu0dsrMEhJc",
	"mZ78KUHsMM7elRZXZjVv10LD0gw8bxLq0hp22VvVmwJfJW9ajo1onEvRcWMVZ8TGOnoqiyBhE3HL9WO5",
	"/gQTaD4kME2N9/nxxU3TVh+nmU8B0ApO1LsL/kZN+UhaQd88rOBv16xPKeT92ZnOJOAqOiQPv/4N1rDE",
	"tS6YeStYJ26pAZDynmrU+iyJFHPTRPkzqMCSq2xFxWBp/7zs86oSYLJWB5wTY4bTX1PEgKUMiqfXNHU7",
	"GemLm8mXk15eh5iMe5Lx9cZh5xfJEIkpQiTPAaOaysV8hbshz4jSdEHMUQW23P3xrHhpGtv4SqIOocKa",
	"4REZM46hajWheupI3UQRJY+sexvQFkFH1v+C+SBCb2TIVTYea3dU5WFn5hXaYAol7evosBbY1W8yCcC1",
	"Mt3VuRzse3Uu35JQbDUJBede1mcZ9tHNwSbhaIXqBk2N/yXjLkhgOMEENQ41ncwqA8iNNnakgXpuMWNo",
	"ENgX/1T8u6yvUQBzgJJUKEUfM8/+lmMWc0UH6AL94DIIY8i0fsj6rHIbBB4hMMycJI7WXxdgsSAf3Lw0",
	"ugXwwLnyojgCg+AqC0PE+SCQgr+z0i+ONjxFYRuSqN34iOISyTzMwg2ZyDGgQLrlCaTOqd1VT9RIuKFm",
	"S88EjyftWK5UZ/VW79oULzeUtFn6zRs1tZiqeDJlXM4/j+x7mrYTVSFCpZ8JlMSJQGI0RSOG+EQXZSsl",
	"wKuvsmsnUi+6dGZcL+0Va6gX5q+ENgxoF1YvPimvvF6hX4KFb9YOdOrFC5PymSanKixhASLo2IVyAK7C",
	"CBtDarHABjm07F9tlhFjoYgxuVNF+g+nBMYYcrX9XNfQfzg15Mg41M+Q2REw0bnvgtzWoT7rlJLaP20I",
	"Iwd1WsFq2OOA5jRfV2PZZT7ZepW3dulNRfMadw106iV9C6+monndXlmQ1otOCiDXC3sF2OuFr52N8CCY",
	"szX10pfQ36pI6u2BvbyNFuL4WwqjBRguKcAS+M1FNpQYTE12c0JFe0QzRaOHMGpzJMyBRibJuc4/4yL3",
	"WpQsX8KVnkH181s7o2rBGRWvzASrRS9hdJXPt1pok7RXv/ftemoFFWTMC5alRM4zDzX1HCwI2yYvSVRv",
	"varR0HsJNvNuNqZMJZssKS7PU0Surt4YaxiIIEr0de3Y+nafHnpYHFQg9yYrrZL1zxppN+63fJRUaM0w",
	"79R3rKaagWgpIBnPGWtcLpiIHHAsI8TyAoW192lZ0ITtT7vtF+3b77xaSDmQfzb5k2g2yn0QcD6JOsZF",
	"YBA8qaifncKFbJsatoxP5d10d6BVwmgHikvzcdc4QT9T67BoHdffUq2Xq799Dz6p13qtsZZxI/krBO51",
	"z7rGNAy6l6fdnbfnx93r3vlZC0wVpy8/ljN2Sm4YE5VOggEaIkj0s8G2Ze6SpTK2QiZwmMWQAY4FUiES",
	"2HjxQ4ZgSx0lA3jQVd5acOcMTf/5gbK7FjjNJDXYuYAMW8VMRmAyxOOMZhwctMMJZDBUEVt2rZUcBeDx",
	"IHjdvx4Ectdvro/NZi+Xr/Wmlsq76vA9wsQawE0tncs0E1SKRmGejFzpqUjkS2MucGJLrV+ZWg7NfEle",
	"1vMmOmaUnD7IfbSKBy4gE68ZDJGb0Hd1VaBt/LkVCAc3V+4oR+yaXCQC72yXPjLvv1Lod8V0pt/hvqBM",
	"zAmonVAu2oK2xyqplnrKwCjAi9Dl9/0OUC+BICLYTHtUOYfYnN+BCiiWwx2pzuRfVuqtl+ykjAoa0ngQ",
	"mNeiB8Hh7uHu0eGubWR+7ogwNYcm13dW3nm8/e5I//N457EI0//KovS/eCjSJ+u+y/gns/wuY56tamTe",
	"98GUsjvFX1pfE+Mp9UplLD4WsXnnRaW/ft8HkaQmyi3DRixEKMb3Ks2X497qhDrt5GEPOsuLdur2uvCD",
	"V5TZ8vzpXJOuRbuRGFc9HSJhfKnfYyaA/E8G477WMYEP3f5bbccl2lcyUdHXfke7RZ6NtYPRr7tcaopq",
	"fDKXtVHrflLHXboI/lCReuaGUJ1rsluOMg92kAh3VHj/jpxOJzpidN1k6p9VTgD9goKaR6iWjhKI4+Ao",
	"EAgm/+Emsg6sO5niXzTCAJMxE1wjmEh5gsmmVnVVal1zivul3MXtY1+zJ0b5axK2qWzjKIwh06Z+x7WJ",
	"jsAoRkgo1RuKxtYXXbvaiQnCLMd+rp8iinGICEdOzu1uCsMJAvud3dpiptNpB6riDmXjHdOW77ztHZ+e",
	"XZ229zu7nYlIYn3pCLVdFSB1L3pBK7jP04TbzOD6oRWJh8FRcNDZ7ewVWRd+D3acfGUmA6DVReucCr4c",
	"58c6LASC46LxlW5cJD0v7FO5mrIX5Y0bWwYavRAXL2k0q+QDc875zq9GM6wJ2Xo8QuMkPpfR3IQp6Bep",
	"uD6F+7t7f+jsfFsSyd1+urv7ZSeW52auzeIljEA+STmTvT9qJjcEZmKi3FoNUA7+qKm8omyIowgRPY8X",
	"f9Q8yq++qcns/2GTuaYU9CGZWXRR+Raf/XGbdKXvgBuSG3Y0nwbHSjnVSCWDW1ltDhXd+V1S/88qEAsJ",
	"n4cajLQ4lUf2NB78OjF9jcQ8Slqk7PDkDqg6ai8m5kBQMNY2Vyx7MPnOzPVmwnfKVLPlbFdVCZgR/FuG",
	"eprH1uFEtzUiu/snIrLnP36jag1U7ekfNY9c7fuNnm2Rnhnu1hCvHZt8uZGKvUbCZDAyWZpNpuNmNvA1",
	"Ejbvs04KvSq50q0MSSoPzqu+U9uhWJ/r2Unyt8aV5j+fwfsiMYkaVqVEKsb1Zr2eN+5XJ4tmSxpp4L4+",
	"8NWjCJx49z8VmfwjyRMo6NMfx/z9edk+hyppouEnQYVHTApF6A8Ut0HgThbxk0V0SDUrpaVfjw65PJKa",
	"4bZozu0qAnFbDf3dFvawFEm1lDj8B5Okb2LvNwZxMQX+xiFWOETQxCLmxLgVpJmH5bsxD9uuSnAvdSzi",
	"lklu8dTsV6e5W6Rr30jsX5HEfiNty3N1xYs3y5sZCPA9qjrfvuB7BvWrHen64H8Ge0LDrL7ZEb7ZEf5F",
	"RMk/NT9Vo3yNFHGRyeC1entxJaL4GgkfRVyJ62oeb6t2gT9A27UUZfym/P8m2/1L06LP+jUNSwy0g8oO",
	"TPHO/Z5ORKpb11IRWUrDASVV2Uy5GBlCYBjBuha93EMznXE7qy/h8+3n/x8AAP//mkKnfmsHAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
