// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3Lbtrbor+DynJkku5L8SlLHd/bso9hOojayHT/Sk1a+OxAJSahJgAVAy0pPZs4/",
	"3PuF50vu4EWCJKh30nZP9p5pLOINLCys9/o9CGmSUoKI4MHR7wEPJyiB6s+QMvTP+70hEnDvnzRFBKb4",
	"n90hp3Em0AUUE1kpQjxkOBWYkuAouEQpQ1z2BSAB0NQFIxwjkEIx6QStIGU0RUxgpAZJvf1cT1DRWlYB",
	"ggKo+6EEiAkCfMYFSjrgjAoExAQKAMkMoAfMBSZjXXWK4xgMEaD3iE0ZFgIROQP0AJM0RsFRsHMP2U5M",
	"xzswTTsxHQetQMxSWcIFw2QcfP6cf6HDX1Eogs+tho1J8XvEuJp/dTndi54pAxEaYYK4WsK9/oYioHcd",
	"0BEQE8wBs9sIZQfyMyRAj98BV4jJhoBPaBZHIKTkHjEBGArpmOBPeW9c7pkcJoYCcQEwEYgRGIN7GGeo",
	"BSCJQAJngCHZL8iI04OqwjugTxkCmIzoEZgIkfKjnZ0xFp27Q97BdCekSZIRLGY7ISWC4WEmKOM7EbpH",
	"8Q7H4zZk4QQLFIqMoR2Y4raaLJGL4p0k+jeGOM1YiLg6FZIlwdEvgdnYoBWMYjyeiFDEcrDic3BbPaVW",
	"8NCWzdv3kBGYSMj6JSgO5H3etPj2yvbdo77i0yQVMznQQ3tM2xWYaISA9FpV9EGz7EKfLwIwTWMcqrN1",
	"F64uIkdBK/gtg1GMRCAHIgJigljQCiYoToJWcJ8svQFqPsd5t+bDu7z3vEYxiPn0Ro9lfr1Pgts5q7aL",
	"kf0gIuQGwDg+HwVHv/we/DtDo+Ao+LedAs/sGADd8Xb4CsfI9vS5tUYHlyiGAt9rFCV7YOi3DDMUyU1R",
	"+Oa2dqmXWd4J4rKXKwGF55BNKYjxCIWzMEaAy4pgRJnChf4zZxkh+gC5oGmKouXP1jety7y7hgpXdpQl",
	"1ntK7t9DprF0CWejogBGEZZ1YXxRqlK7MeXNOiX3mFGSICLAPWQYDmME7tCsrRAPSCFmvAUwkYeDIhBl",
	"shvAMiJwgjpAXqg7NFMoTLdAMJyAJONCovshElOECNhTFfafHYBwAhkMBWIK01TOfgUUn+9NL4FjdILH",
	"iAsPuicAy3LA0AgxREKkJoIFl9haAjaIVFOACYhpCGPABWVwjOrvY9QwxnG5I4NZ9LDVXsFj1Bl3AJ/A",
	"/WfPj+Aw7HQ6Tzr1t64VqPb1wXrV1XCAhQRpBBmXw8mxGSIRkjfAAXXAUxR2vK+qeyn1sC272Ns1DuSC",
	"Ms8uya8ggWkqwQcTeRkTKMAgmFAuZOFRjmDlr0Ggt6oFBsHh7uHu0eHuIHhSJhnMd3lQUMgXNTgK/s9g",
	"EH13JP/z775dXTh3Ru9xhNhLyJHvpJOEElCAhUYpcVzaaDkor4MPJIRqKmKT69plQywYZDOQIAEjKCBw",
	"Ou6AG46inL6IZ2A4UxChqAIagzSGBNmdLT3qU8ruYgoj9cI+AdMJIkAwSLg8KHlmtSUCKAykAYULAglJ",
	"MDon8Sw4EixDHtiBxcO88mNiH3W9JyX8v8Eb1/SqfL5trfCsKFrR2aGWvJgJ5YoYRETEM8CRsKchH5gd",
	"LiATIEL3OESge9HjHXCJYNSmJJ4dgVCdqkShsl2EGQqFPk45yux/A1kNGNp04b0HEYrxvSoylCgcIyLq",
	"R/a5FciHrYENcHqVtXIsv/c///1/y7gdxJSMW0CvcYrFBEAQI3lJAWWAZMkQMU33mlsPCAVTSaHyFIbI",
	"ixEZUt29RgQxKLzU/THNJOgDTEKG5JOGIrvnprWz4fqlkqBbJQWBIvxVfRT9GY4l3w15s8eI1dC2vVdr",
	"4WuD865SFOp3Tm5pggkUlMkPBmtrRlRTsA03zBC4TuclwrmxlalQbqeI7IYmkigu17aEekMDQ2mX29w3",
	"9v++1PvnHJfPztTtyPf7cyugBK2LezzbtRaZ7VncWv14D2Ktnqrns1YnlUNYhlC+NGzsW5xgLUWpSkV0",
	"OYhVBYO7a3xg+eUO08yDai5udCfylstp8Q54pWkaiToYVuTyEMr3mJLa61mmZHY73z/zobwEJZTN6oP3",
	"1XczvkKvNNXEBMgIFhvMZP/Z82Qj0UvtKOadQkgJFwxisuxRxPm5bvLQV6BkreVJKiHjfimDLlPCIsAx",
	"Gcfl18WIzfRL5LKgFwyl0HCaV/L10X8WrOQpY5QFreCG3BE6lShMopAYCRSpJpqjNH/JJiuzsHrq7kRq",
	"hc7MamVerlcX2bnXCorF1Irc1XnmYZfrL1LrX+Ikbzhidc6aZaTL/XRQxpHaO8vqafmn+lwjBK1scIgk",
	"zwwySQlIrhlzSWRIWkL1IHuDWhSpupF3GhMlR82fT+4RWoHHeGR/D2P0pANO0AhmschFjmZWUBT0hZwJ",
	"l8M9HitaSvIJjFLxBOCRmpKkTfAIo6hOh5XFcDdmJ9zPbX6H07bFR+2UKm7EkJfr3LT3NM6SCplfpcy1",
	"JBcqsjQC96qFXLoi/+oyn/JR+yneG4J/yxBwD9rt15yQB2N5CNcwhji5oDEOZ5viLr0bl6Uuq9SgWpCH",
	"FPx9E2JFSR706CWKca2nvS8J9W11pmbW2OPtUoSDp2UNJejj9yCFt1jLfdyLaSpLgMACJXw75x4UFwgy",
	"BmfBBjfqsgqWkUYd6oGWKCdoNdyzCZ062GQCSRSr22fuh5YdTBCgU1KVHCjOKqH3GrfYh8+Md7uGxEav",
	"RaP9+S/xVrDCWQ0dNFx5I6DzET9WdmcwdITSmM5QBM6Pe20JGTGGknlUkj7KgHxtRzAUYAjDO7mfc8f2",
	"oQJ3PutwiPwqSxLIZkvSPGV5GG+md94gGIvJLGgFJ2jMYKQe8zqNc0bduaxO05SnXwzaWMWZTWMdDzlT",
	"ruAla8pVqgtrOopjKGBMxz2Bkks0msO6V/iWUrO1EFB5ZI1QKxBWGWVp+PJ03SgWHcGYo5oo1BGDK520",
	"mQmQ+LYFYEzJWDNHRtw/wuOMNfF4uq2f4LMdK1ogp6XkMBKfpZBJ7O/FA+EEEoJir2KiYNnSCAoETF0w",
	"neBwkivMFboSFKT6qPPKGeIa0cJ7iGNJ/PnVCAIl/kW5hI27c3K3UOxfzn2jWh3cwxhHVo+uNynMGNOy",
	"T2ULkKsn3NEWYzB7MmYtxSSWhzR5zCN5ZdAVHssn6RL9lvl1OU1VC0MA+dAx81GJ/wHHY4IiEBZtwYjR",
	"RK31uOvRBJTsE9YgCvLmn1vBHSZRfR0/YhJJ2IRA76rRzeWLsM/I5enVNbC6f8286M101lvYOSRwBjAZ",
	"WTYnXyQikSLz9enGWFIFPBsqCYvZKsmPdMBxLj7VYBx1QI+AY5ig+Bhy9MWtHJTeoi23jHf88hatU1nr",
	"XM7VxvWRgLIrbhDa6ii3CQQNgRzwnNbZYt+6z7pYOQc1A2nOHpk1bn4Nc8FzCYR/YjBNkSR/aEYiABUn",
	"2w4ZknADjq8uWyChEYq1VOsuGyJGkEAcYKrgBaa441xJ3rnf68ydQv2ioocU6wfjCoWURF5RlmqvNeO5",
	"jZBChljMcqGWMxE5jFZ+ann+wX5QF++3AvQgGJynKMy5ihoUlxmEmsJfdgyg0PcH5VKFQlBg91jhL7nP",
	"KU2zGDrKlO5FD3CFFOTeq/py5Uq1niSZqDxHBWCwJsQrX6Qh5Oj50zYiIY1QBC5O+8XfPx5f/dverpxO",
	"B/ShCCfGcEtptXN0jFEcyVcGuvAwD6drxFc6kuFMIB9uUFienXm5gh6JNJAZfY+FCd1GK7oUNv4tg7GS",
	"rKjnV46bYPIWkbGYBEd7nlEz7MHuN72Tr3BqziQ4HPv43hv1PRcXqecGKU74Ds2AbuXshnn+MedZ+bks",
	"MckLwdmK3+YzZ19hYyrI0sJ2CVS2gB0bWNsC5mAqiUMY70SIYBjvjCCOM6bV01l+v9XSHY0rbzgMgEeF",
	"/abHjsGp6r/Gpss6VdQqdhNQSbXnB7HUBZQYGOf2EzUbHFOmWc9Co2pOpQN+lNwYCJ2KDIGu2joUtcAJ",
	"Ilj+K3foFcSxntT6opt8Rl6RTYnALda1PLTUNYdbM4Mo2cCsJZDzWK5t2k+DrHBTeWYTL72e+nQpNn09",
	"ESeJMWme7e3nFSDHwuVmAJP3k4NJ6rFj2qRjrWCvXBbht3KoGevkvRToLkIC4lgrGilBAMp3K7fXM8yq",
	"semx5t/yZbjMqYSFe+o3G5NfC8QjObJMcShgROOYTiUv9mNBrsghXbYF3HBkTGjkaSlRRyTpYfPshtqg",
	"GZEs8ehLIRfXDBKudxQ3mfbIeoUpTDFXkbdFkeb35M6Zh0XOhFAxQayEvyVj15Z9+Tkszr2GjW+yBBLA",
	"EIzU+2DqAaxfOblH9vzgkGbCzDifnpduoUP1qkfzTIbk6juWp+mM85qFnKfYjSnk2oxL6dKzVA/rEvPP",
	"n3qJeYYg94tNHg8ZRqMnQNco+AU75iO+1Eo34QntUA08oOm65YOlfGXFwa6OiBbL7ks70lIgSEfgmmWo",
	"BV4p0SAw0lZXuizLg1agKjjy5OXEx5XZmb4qX23Xlc/5SAuX3uCkYBwUCsDDrpDEWaIlX4JWcH3Rf4+Y",
	"4i20yNkWaMJGbYSkaupVwxBxjocxqv6wiO8CMq7NCmYkVH+8l/ytrCERWCZ68jkaM8QlmNykETTmAfJx",
	"slX7WSxwGqPzKUGMq3nd4xCdoJAmCeYcU2M48CpGSJygWEDXCsHWLn1e7ihPCaNxnCAiDEXtbE6trLw3",
	"jUS500VjnXzjG2vkJ9JYozydS5RSjgVlM+85yeNpLKgdpluYH6zafHtk6ofviPVhOAetP7jHrb98kUOf",
	"c6tGeFxViWxAIb7GwtPnWvRb8b5foZAhsS2KcFvzeyNE6utr3mbXTQX/tVkQZSf0jY9xYaNK9KeU+awu",
	"Xd+P7VlEKD8Tj3yIuYaH2zAT9FoILk/npJntqE+JxN65rjO/K+VdTHS1xR6MheKGAtNosZjK7d1rI7SG",
	"l199eXMwB6Pk9CGVT4nfhp9RAlBewToKScpYziLKYqW8wgninQGR22FqYA4+/g2Y/388Am3QxyQTiB+B",
	"j3/7CBIjNd5tP3vRAW3whmasVrR/IItO4Exub58SMSnX2Gsf7Mka3qK9fafxTwjdVXt/3hmQqyyVtwRF",
	"QB45FFROoi0rHuWCbUhmRmFnPHVkN5iAiZxy3h+6R2ymvj2R435sfzwCl5CMi1a77cOPauP29kG3L6Hk",
	"EHT7unbr4xFQdku28l5rb9/U5kKJwfb2xQQkag91m52PR+BKoLSY1o5toydTbXGljV/LazkstkQS9odO",
	"kwE51ZbIcufAbvuwtfe8vX9gjrSztEfXccYFTTT50CMjOk+PUuXIlJpJ+4ZHIFQdWY8vcyreeVQl404n",
	"mGgIVTJlxbyWzWGWwyOKDCo42YJrWsFk4gJiBkKaEcHB49Aa1+4IKmD8xGizU0VpKddF7SDWAReItVPZ",
	"NJ1AjuRFkyxYZUKWPpSgQARIEQNcoLSlLEqh/B0qazEEmRgiKDqgkNEY5pGDEDI2K0xiK1M0U/fIpHM7",
	"4bpOQPkayRv5K1Wn4bD4yrnVRCxgCMCYIRjNgEAswQTGSzL3ki++0epsD7rGhUpCMfLVJU0Zdn3IzO4v",
	"L1BRvcxbdqbtWGvLVtqYhhGbFluTXBfm2Xoet8tDc4pIhEg4k7yHJj0v0WgtqJ7bl2u4UXLGGmEyRixl",
	"mBR2HApbaUsha3DDHnGAHky8higfyQeDLvl81uhFV7K7KQ9lvINlyRgLQBl4c319YWuZt16297sMOyvy",
	"D+0u2cwg3w7rDq2nIIdXPJoAV2+6LeOwLBupGQ1pNGuBHw854IqdyWWkxlrAPz/nonTFMnJId77hRD5t",
	"EXiMO6hj7SbNYeSTn0JuLUueLHuF6tqY6jGuCdRbgGU/CPMZCSeMEvxJ32dnm7R0uw6vGBkjWP3qtEAI",
	"U5Epn8SaE68PrC/RyEfXI9bW5e0chN0zk0SEOlFjtCZHaCkJam4ibNwx9RQ25A3m45T1Lac1HbHyQZqF",
	"OWZj6WTGcajOJTeFtZ5XZbOwpoAr2trLdB6UDZZiOESx2rlRjJQnpDXozr16g9Hz/Wg0fDp6Fu2H0XD4",
	"4uDgxcHz/eGz0d7haD9E+88Po++fPX/6YhiFh7u7uwejXbT7dP/FPvwejQ7DA7Vp34zZvhmzLX8lrWBw",
	"Qy2F6WgNM7Xb1a55zZesble9pSAGKBmiKPIRjT9NkJgg5nNLt42sMc2QUhFqXwEHCIaUxgiSPI6IDo/C",
	"F4YT4XX/tYwrhlSZz2BmgpzwergUG/DEUlmj4kZZ1WpOayjf98cCjiWJo3t80skDsXAwnWh2HpOi+5/k",
	"i5GPYUl1aFvJAbHIGUv9tQMukWG2jaWP9q8fkG3JoNzgMx5RlHz8FJu0Acyr9nLIWfGQ+c2fKipUl9Bc",
	"7KIGo1kDvZpzEo4norZRl0yTPoelPeFUUAU+j1+xdYDV3jZ5BnvUrFvy2cQcsEy5Lhl/zd4IDGNI7lre",
	"SBEZsb6bimlVfZoP2kOq6me5dbfKjVCr36n5c6vZ363QzJoquVNVdSu37P42h5TzOj1JoHagrlUos3Pk",
	"21o9dkbtoSh79fiESlxXsNA3UT5IFZdBj6NU+d3BRpI199a7wiZtMWHJI0WJl7z/v5hNwXzfsQYLgxX3",
	"/ximcIhjnL/Ky9PmblNJG5aeCMOR5JFYymdAeZ9G6z3956ppvgMrrVXxMk3gdeyYLhUGE2Ydmj+rL8Q+",
	"xo2RMi/ta219epr6XWQVWx7nduWVcxp7g/w5xVUOOTSfQ0oICo0JRX4v6pvBta6hd+J/PEwx6J24BjqV",
	"Efx3SLfsO6R4BTXkUJuPkgf2Mo+qnLexqf57KShfCInrIYYJFhjG+JMWnuRhLo00s5XPWVDbrAWQaAwK",
	"Vw5AVLqwlVW1nA1c8XxdUwBfnBMb40yJza34AkRlA4LcyLd2sAKyMRIbUV/FSNeqM79Zoh5ng8U7ndff",
	"29zAXl9AHYesugkJEhMala+payx0Q5CydlGmQKGgbHaJeGnS86xo5s3Y6XletfKoi7amQvWuhuEvEc/i",
	"XMjpBGIDkexYR+sCUAiUpKKQvls5lZpyHZpGMI6HMLy7bDDnu3IlW+6gpt98PBTHyptb80jQTEoHVs7i",
	"2PA5aRbHHdAd6lhiI0CoqTiF3PaFImAwki7iWRgiFKGoA45jBCWc5DMi6KE+Fbt0vWYdsc0vT+D4kwc2",
	"Tx9SExlUjy/RDyagd3qsQhFx8PhH/LIF+vI/r+V/KAPX+OWTfGH59HRTHRRlhgTIDfrWDUZk9X8CjRkW",
	"s+MJCu+a3tDmujXpa+mVxbYFCGUTkCIm8bV2SluTmGt7iblCc1gdU89o2zRc845skYhr7H6BNegK216g",
	"P+uPf0O4VcK7ZpG5od0qCNG3gGKkeXXcOTTXy2fXXKWY95J73Whwa5iUJgivvSyV+Lh6lAgRgcVsyzCn",
	"RFmr8j/FlVG8T7GSBZyPrJ3vqlelywVM0pJet+j8XrUs+N/l9Ljbu6kmBJY+TMvLizTZ+olsFwPUp700",
	"DmgkeRzb2fwi+fHAWne+cv9a/vKmK7wAWdTxxIL7/dbGpV2LT8yj2m5B7lA1cqmEzP1Sb1VlA7b4TPl6",
	"boJON72Ab2/r75E2QjcgUrWMdr+sCKeVWVchrVJcmoWn3De1BdUWw+w5rxtDrmcBe858sWpqFqqKSu35",
	"Y6uf24AsE0zEkQrzUYovY1gHG46pFlf7EXetbBgKKYu49WBCSuE4RE60PtkrU0GIPyqC/6NVmWBuIOcR",
	"z5UnWsVjieaIIk0o40QyMjlnYAKt/M9//z8X/jCxhgAinoEI85AqFWgISYQVO1BeGjdWIOorB2k2jDGf",
	"mLBZxiZOGcbQKQHHvSeAoTFkUYw4zz3nlC++dqeVbBPX/E7B4kjmRkdLVpwNUaR/xptdrRd5/J1ipTNz",
	"/OLOj3vV6P+K/YDzAgdVQthoEQtDnMb3WswCSbnjTrAQxNfBx+dXHkTsh9v3ZQHd+VVNH1hJK9CULeFa",
	"Dl/KYmD7quQt2G1MW/BlNF4NSQrcxayI0XPvl5XOJjctX0QLm5DBa25AeXJ50HvM77beaRFheIvdVk2q",
	"0izIRzLr2Oi45lvG85JpvD7Acl6jIgTcT5CZx+yYYYFDGHsi0K3y5pYn6ga4q5cWg/tKnQn5iu0kfWUL",
	"HRAds4wGSciVDk8vC4YqsEcTpLsKrOUiY1pTsS16gpRdXmpqeK2raJ5dxQyTbxz5oe6T5ZsTpzFqUFfH",
	"dt9Cge8LbYMRs29sJ+dqVrwBg8qk3nbE58oje5MZG2Kx6uJTTZDCtANGjgGMw0s5AuCGW1hxefFtorYw",
	"iFYUXF/ntgmRCkmDlVFOyb2n4iwERTi50PlvvKpnC0qqIjCZcsrLr2mrtSG0nUdGsFDWJC0Ta17Hp5Y8",
	"Hs9GI/xgqCo+QXHc5mIWIzCO6dAOpuavRodjiAl3IwPGFEZID6HmlMAHGw5p/9nzUmafX3bbL2D7U7f9",
	"89Fg0P5nZ6D+98tgcPu/BoP2YPC3weAft989/o/l6j35x+PBoPOLrugr9uYPWmxBquXrG8R6dpxrTTd5",
	"2M1VXsw1rY+Lpq7c28/ccye4rnkegGkreR3BII61FUwoMmUqZkJrbPqaWBW9G2bdeeY3xYx1E0DP9YZ1",
	"E4ftDFkxJpGnXLF0WBfhu90sH08pBwMd0lkZZVl7FXmU3uAp7gl/kRhK7qO+/gNYGFWoV6/kz7Rmzz4n",
	"LdW5a5u+BfN2VyxuJIbbEx5bTu4KIbKMo4a5kDo+CiJ5niv9gIHHZ+fXp0fW3ci40hlNH0MiY6QUi21Z",
	"1w1jHfcrp6SNx4QylJvD5RK37YkTt0G+5B1t5qPsZWElybExHqrhHk0DWB/KdXstOikTRn70XqI7toPY",
	"9QyiG4JFM0rPCie+jV7tqEFs4SDc0saWH5PA/7a4MOPe+RwRKugsFlFAg3sbVmS717drdLDCBLJoqvwr",
	"iXV6xmRsLXBLiYe3b+9o5mAjVn0xi0fPfm1R/7BS/H2/KuxcxQvxh9q/RENKTSiXCzpFDEXno1FJV9ad",
	"QixUXBpj8abDHo1iHIoLmPEVVROlBTlTq5U5s/WUloUgpSJ3TZ7i0jI95VVlSanQtxmeatX9WXDGJUy7",
	"nLd6rrEwl8mJ6oseUsrrjg+nMJyo6KwhZQzxlJKIGyG4ZY/1rTIehDntOdNeEwv83vUiSpcypHGsLYRy",
	"h5BG6l9OstEgVZIdXWVPb0T03jvsek019OHUaLD+9fYs4clnIfqSUgF6J6t2FTYu1Mrz3Q4/akefdtus",
	"/WPZfsq4ARmdEOECxnFhGmZVGiFNEq2QwbFfB6t1O2s/97W4C5asPo3xWAWlmuPrlGu9lNYlpIRnCVK6",
	"Fq2H6qiIb052mRC3td5qiIl8hLQzu9yUjg4Lp+tiYTamA84TLIQ1iYME0DhCzDhp5Co1ve3GARnFkd+v",
	"ioZYEfurnWIx56aTLGpsfpr5Y6uvpf86nOcv8pV9kZeE46oXnnvz8utSn0WrfM9XfAprgpEF1rKpqqns",
	"HBNI4FhHklRgpkklld08jLNIlqgjMN+d1G0RnRIjqZI7bkIMe0ygTL0rHahmPe5DrzDvIidMt9rp53V2",
	"PVpLk6lnv1WzEpe0sza7X5i0K+3AFkm7er8rGJYUW5tblaTX9ASqANrnmTgfmb+dWH3raLVKk3SG8JS6",
	"o3obV4IGlksXKq4wv1sYTWs7Aaxaf7KwXF4kZ6SfCrvpDhR+w/xOh9+v37oUikmT5p8hZaAPZB1n8qr7",
	"cp/z16LG8ARpbjzVbF503gQ+4CRLigQbMI7p1PUL1R4+gubBdTpALcg2KBB5ntkSQBWQgUqUcW9sCREz",
	"EZmtpYuSb+mEukXYrvyjiiB/BD5yHQGL6xQhLfAx0R90UCv5YaI/qPBd6kQKpcbjfxz9std+cTsYRH97",
	"8o/BIPqFJ5Pbf1860tUpCal8uZZxHEGmrgZU5TakThYKWEh5c7NVi1HSWKcC1Nk5lo65qoe6MI3t75em",
	"k+blVOKxehwOqlXmpGYyiREkaGgPlZJger3YG/UplkMtmEgbewfR84P96PD5wfcHIYQogs+fRvDp7rP9",
	"0Ytn348g/P7p/ij8fvfZ7u7+8++fHg7D71/sPn8WHh7uvYj2hrtu2IWQs+AoaMv/vTx93TsDx6eX171X",
	"vePu9Sm4PH13c3p1rUoHpN/rvXz56/FL9q73snvy8m3/5m56Of1w8v7du5PT3e5Df//dfv/TD3fnJx8+",
	"nX06+/XDT6/in1+f7p+9vpycnXT3BqSffHh2dh0lH346PTg7+SH58Cmcnl13p/1fPxycnUzwh0/hs/7J",
	"h70Pn8ZP+9fxXf+n3rT/6m56Ov3w5kf6c29APv26e9x996Enf336dfek+y48eTfunr552T8+2D27/OH6",
	"h4Ozn85jhF98+OnuZX+n/4menbye9S9/zD6d7u4MSPjj3ew/3/+AHt78tvvQI/v7H47Pzg5+Pjl7eJj+",
	"9Pxt/G58gH99Te6vxLvz4fNut9+lr4+Pf3t91X/64mW3fzwg3d1xt396c9x7d3LFHvDzOxYd/xi+PZ5E",
	"/ZcH0+97vyUn8c+Ty9PXwzf949Or9+Q55xfd3vjnt9+9Yz+I6YAcXn7HnqYYfrj/+U4wfncwO+5lnw4m",
	"ve9j+iH5z4uD6PDvA6K2/fTsZM6RfAua8i1oykrd1DDMFuKn1Pv8Chm/GiJv++LVNVYt8jf4WYEcxzta",
	"R4PsEx10pME1FNoQ3nMy60ydQCz2YZlADoYIEWA78MsHimhMTaK8BaK0t6oD+XSpnEoltybQk1RmGsMQ",
	"mWryMiqRx2MT9OlJC+gpqCgdCWJjk7RaiztswK7I1nKucm3vvMMpt2B3DEVQQOuArQkxMMLatVkApaFT",
	"6YB94zdkC3PGLGUo9rv1a2Ps4tjqG0CZXYhK2GayEysAUqv8snu46pYpWYN3JBWgU6k8veBXu9QG1De/",
	"uY5Zyfr8VjNeqDM6C2ayCD04NiqbIoqmmIWKIYDCxMRxUYXy03WwxHKeYLbFy9niAJKm7hL8pdNry13S",
	"Erl0Fh3BGoZCno0vLuLyUOkXAHqraVrIqainU6v7yHWF9omtFDHuOxdfvkI3rxrXmR1cQPM8AWXbrQ3j",
	"pLUCJU+5XBTr49qNBOqP96Fwmwk90PmVUwIe22BETZ4AGz6AXZtM0OC8PCGPNStRKZK1J79K9lYoEIzc",
	"n7tghrnvxS7w4PYiu5R0/pxtgHWb5K0NFVe7ibVOmlCfpte2h+Udy7ZFuQTdO1VPKNhZOU1gPckX8u/D",
	"nzXx3ysco2Md7bYhV7kJhauOeIRjf0jX5vZK3AMEehDg8c31q/bhE0k0VVKzOoNoNVnceBaynpX+rAlG",
	"joRreb2F3KjmsDuyNA+0U9+hMaNZ2hRDOVaOfrJGy5EnIuN+Jl8Z/UIzQLIEMRyC3kkHnGiSUhH0g4BR",
	"KgbB3DhwCwK+JQZZNc4wRcwY3qs8yR3wgWaKf9dznpkgJQyBEUxwjCEDNFQRyRWBC2IElbDwE2LUxu7f",
	"ff70qYIHqB/TECemgQ7P42vzdH/3SQdcIZHhaIcjMZb/CBzezcDQCFFB7uOsyGRCRbGxOuReZTFKuifX",
	"KTF+sa9yev7IgBlHbO5u0alK1PsFz3OduH4rQfsWFCEudlkrFUjp1q2XK2fIaZwJdAHFRPVQUyzkaGUV",
	"FYM/l1MttOsYi0s5YT+BVHIafa1CpDsuJSaF8CoqF6tocWLBm6BfRaqvhkCatngxj1B0VUp4XfdtUGTv",
	"JbrH84hEXSonnXFUcLxz51sLCZdPvjZqq0l51BT0dEFI/cWzMRfSnPzSD/EbFCdfJ/fVv0huKKUbSmHY",
	"pDzVTFdeyxf1FUQojeksMZEZc/1NkMzaME3bxRAe8Fby7zn8iA5zV5MoOfdb9+ANR2v1g/I5G2LBIMPx",
	"DBCTBd4mfOUVrVPuz+1e54CMMXlQN2McHAV7nf09beWvs+8d/R4gAoexBF495QlVoZ1/+V39FRzZEToh",
	"Tcx90sUaDwU75qNWGQYXDI3wg8ohbERuOITHNJME4kErMMyWze4VHB3u5pt7HGdcINa78NNler/kkzDH",
	"l8duqnrMJWJV/JyRzTnnDVQ/JuRwDJXWVi3NtchRuf+1AyCLEANDNKJazMYKEZoesXQUv5i5ykpRpsM5",
	"zmASB3YRbXqPGMMR4p1ZotKcLJuv3uu6frt+OrGGTH21l2wiRLrkU0bcNCOLHjN5UBfeB01+tc9XHr5C",
	"VrfWqYI6MjLLQlT9P9RUOLpHzFHbTxkWApGNn0JWfwrtSwaL3BpgziOpHR59i2c5O3Rz+dZEj6CJBNmR",
	"MCoEyUXJ0g7o6dAS2vAMgd8ypMwuGEyQQIwDnoUTAPkRGAQ7Esp3BN2xOrZ/qNp/V7V9NOfc5zY/vq//",
	"wlqIXBrU575enni1ZZgugnRIfsUGbVHMjYDjpYNrrN7t/M1oQgDz9qAvsbEnc2Td5lTV0VRZMdFENtep",
	"Xgr+RkLVnE1Yj9QwUbrV9VHaVP2MrNGd7kktvDH8h+59ta30hgkq0W5/CajagIGcPxVvLByPCKm0ievJ",
	"yTzhmv6SYX4UXF1kcVw4fed6yqA3OqPiQgtlg1aD+0ZZmvDIbfPIZL7gSKiybjyFM/5IS0XydBhppgzE",
	"dRJGlcep3OpMlpQaJRkXeRYNFTWqOXKmHjNoVRejel3SIEzuT96P/FHpS34y/c3dZz8WJFRoMtq1p1TI",
	"4fMXxXBbwO2lDj3BWGwEFkWcaIqFjgx0tpXOGEMbHsxFHh1w+gBDEc9suvxH+W14JOs9Kl/hRxoiXBPJ",
	"r3brW0Fauj3rnYxzA9WxmMUuhXvnbaTiKQBDY8wFm3XA9QTzPJZbkRPFaUioNhox5sASjdjOWpLOjCkZ",
	"y3+NAImyhFshUIFyuGvgu9UHIJiTT3wOtdWUrRhr7705kUdcDt6Q/VsL/VNIKxfwXXqWGzBejQnXj1bf",
	"kZzbDRlSmqgq6l1/b3JJsMfB+cvS941b3LChc3PiH/nER9uYeyvQKSuXFfMWszS5Lv+i2qKMiDXZ9pJp",
	"i8n3WbDmhrnw7vRyZ1Zsq7eDOTLDQli4uKu/rgbIc9VcQWdxtPWb529dXICl72pfBe/7lsfe3ZJlmfIz",
	"mKDIZMrS16UsapNL9RCwhpisEbBfhqdekZd2LJ3rTul5mWRN8mw2Os12HINUcl5KMF6E01TE5wTeo5bB",
	"NUYyxlULPRmVZYyZuvrh9FisEEJFET9qTdOjorJiocrhbPwp2+V8MCV5cPg5toI6jpKysZ9CbpaygoFg",
	"hGK0zlg4jpUzK1I5u5cfb1yKiVQ30votU8+lSRRY8jBw2HQnNHJuWaYT2WhDO3BB0yyGjuOxfn864BLB",
	"qE1JPFs6IfsiyzMnytzzg4VBDfpQhfo3fhR3aKZ1DkZz4QoQbComysaQ4E865EkIBRpTJn8+5iFN9VeO",
	"YhSKJxa2vUC13Pup69eC5/nWpd443yE6DiBQyKfQZAK131uSQhgoh4AdOfYgAPogmtI8utnAPQMSQFP4",
	"W4bspqphsUodkburaQ3EI14Eo3AsEyFx1r1ughjHbq+Oxa60vzhSxoPagmagkfIgyIN68zxKMjfVI3CP",
	"oYnHQBlgadKmXDBkBS/GuVx2lsLwrtodobpeewglLJVngTmA9xDHNki2FdBYgajpcEmRjF59z7TVvy5s",
	"D01bdgFFOHF883JGZW6UwUoOvQaEZQIFaOsCk9HFXSaMoiB3ClB/JfReYaxyAOgCEP2WF13ww9X5GbjQ",
	"hFYuCfdrjP1T1c5UkkGIXKeCTu1dpek8k4Z6TDvPlr/LYBQj8XWMDTbp7JTcv4eMb9yPJJI37sRDmf1V",
	"jSnW6Xq+OOfz7fJyj0ujbfdzj5dl31ujmFfso1/D1HQl622tVMSSAWdUmPcJEiOzlk+Hqm9pG3qPmKMs",
	"LixEOAt3MInQQ+dXvsGLYVmEboyYuDTBONLmCE31dU7KGb4qDgnKrkT27fcOaPSTtx70Nv+2ov3kZjis",
	"O7xHTL1A3GgN8gTLxkxCDYzJuANeqbf9aL5//CP+qOz4/ih5VHZ8fzR51Oj4PhhE3zX7uqeIhYgIr+7s",
	"WtuDmnK5a3pF2j+A4fFYcgm+ndQUqpYB3aO1Q2aWgODK9OQPCWKHcc6utLgyqXm7FhiWZuDJSahLa9Bl",
	"X1VvCHwVvGk5MqJxLkXHjVWcERvr6Kks2gkbiFuuH8v1J5hA8yGBaWqsz48vbpqO+jjNfAKAVnCi8i74",
	"GzXFI2kFfZNYwd+uWZ5S8PuzMx1JwBV0SBp+/ResYYlrPTDzVrCO31LDRsp3qlHqsyRQzA0T5Y+gAkum",
	"shURg8X986LPq0qAyVodcE6MGk5/TREDFjMoml7j1O1EpC9eJl9MevkcYjLuScLX64edPyRDJKYIkTwG",
	"jGoqF/MV3oY8IkrTAzFHFNhyz8ez4qVxbGOWRO1ChTXBIzJmDEPVakKV6ki9RBElj6x5G9AaQYfX/4Lx",
	"IEKvZ8hVNh5rc1RlYWfmFVpnCsXta++wFtjVOZkE4FqY7spcDva9MpdvQSi2GoSCcy/pswz56MZgk/to",
	"meoGSY0/k3EXJDCcYIIah5pOZpUB5EEbPdJApVvMGBoENuOf8n+X9TUIYA5Qkgol6GMm7W/ZZzEXdIAu",
	"0AmXQRhDpuVD1maVWyfwCIFh5gRxtPa6AIsF8eDmhdEtNg+cKyuKIzAIrrIwRJwPAsn4Oyv94mDDUxS2",
	"IYnajUkUlwjmYRZu0EQOAQXQLY8gdUztrkpRI/cNNWt6Jng8acdypTqqt8prU2RuKEmzdM4bNbWYKn8y",
	"pVzOP49sPk3biaoQodLPBErkRCAxkqIRQ3yii7KVAuDVV9m1E6kXXTozrpf2ijXUC/MsoQ0D2oXVi0/K",
	"K69X6Jf2wjdrZ3fqxQuD8pkmp8otYQEgaN+FsgOuggjrQ2qhwDo5tOxfbZYRo6GIMblTRfoPpwTGGHJ1",
	"/FzX0H84NeTIONRpyOwImOjYd0Gu61CfdUhJbZ82hJEDOq1gNehxtuY0X1dj2WU+2XqVt3bpTUXzGnfN",
	"7tRL+na/mormdXtlt7RedFJscr2wV2x7vfC1cxAeAHOOpl76EvpbFUG9PXsvX6OFMP6WwmgBhEsMsAR8",
	"c5ENJQRTE92cUNEe0Uzh6CGM2hwJc6GRCXKu48+4wL0WJsuXcKVnUP381s6oWnBGxSszwWrRSxhd5fOt",
	"Ftog7dXvfbueWkEFGPOCZTGRk+ahJp6DBWLbJJNE9dWrKg29j2Az7WZ9ylSwyZLg8jxF5OrqjdGGgQii",
	"RD/Xjq5v9+mhh8RBBXBvstIqWv+sgXbjfstXSbnWDPNOfddqqgmIltokYzljlcsFEZFvHMsIsbRAoe19",
	"WmY0YfvTbvtF+/Y7rxRSDuSfTZ4SzXq5DwLOJ1HHmAgMgicV8bNTuJBsU8OW4al8mu4JtEoQ7ezi0nTc",
	"NU7Qz9QaLFrD9bdUy+Xque/BJ5Wt1yprGTecvwLgXvesa1TDoHt52t15e37cve6dn7XAVFH68mM5Yqek",
	"hjFR4SQYoCGCRKcNti1zkywVsRUygcMshgxwLJBykcDGih8yBFvqKpmNB11lrQV3ztD0nx8ou2uB00xi",
	"g50LyLAVzGQEJkM8zmjGwUE7nEAGQ+WxZddaiVEAHg+C1/3rQSBP/eb62Bz2cvFab2qhvKsG3yNMrALc",
	"1NKxTDNBJWsU5sHIlZyKRL4w5gInttTalanl0MwX5GU9a6JjRsnpgzxHK3jgAjLxmsEQuQF9VxcF2saf",
	"W4FwYHPljnLArvFFIvDOdukr8/4ruX5XVGc6D/cFZWKOQ+2EctEWtD1WQbVUKgMjAC9cl9/3O0BlAkFE",
	"sJm2qHIusbm/A+VQLIc7Up3JvyzXWy/ZSRkVNKTxIDDZogfB4e7h7tHhrm1kfu6IMDWXJpd3VvI83n53",
	"pP95vPNYhOl/ZVH6XzwU6ZN18zL+yTS/y6hnqxKZ930wpexO0ZfW1sRYSr1SEYuPRWzyvKjw1+/7IJLY",
	"RJllWI+FCMX4XoX5csxbHVenndztQUd50UbdXhN+8IoyW56nzjXhWrQZiTHV0y4Sxpb6PWYCyP9kMO5r",
	"GRP40O2/1Xpcom0lE+V97Te0W2TZWLsY/brJpcaoxiZzWR217id1zKUL5w/lqWdeCNW5RrtlL/NgB4lw",
	"R7n378jpdKIjRtcNpv5ZxQTQGRTUPEK1dJRAHAdHgUAw+Q83kHVgzckU/aIBBpiImeAawUTyE0w2taKr",
	"UuuaUdwv5S5uH/uaPTHCXxOwTUUbR2EMmVb1O6ZNdARGMUJCid5QNLa26NrUTkwQZjn0c52KKMYhIhw5",
	"Mbe7KQwnCOx3dmuLmU6nHaiKO5SNd0xbvvO2d3x6dnXa3u/sdiYiifWjI9RxVTape9ELWsF9HibcRgbX",
	"iVYkHAZHwUFnt7NXRF34Pdhx4pWZCIBWFq1jKvhinB9rtxAIjovGV7pxEfS80E/lYspelDdubBlo8EJc",
	"vKTRrBIPzLnnO78aybBGZOvRCI2T+FwGc+OmoDNScX0L93f3/tDZ+Y4kkqf9dHf3y04sj81cm8VLGIF8",
	"knIme3/UTG4IzMREmbWaTTn4o6byirIhjiJE9Dxe/FHzKGd9U5PZ/8Mmc00p6EMys+Ci4i0+++MO6Uq/",
	"ATckV+xoOg2OlXCqEUsGt7LaHCy687vE/p+VIxYSPgs1GGl2Kvfsabz4dWT6Gol5mLQI2eGJHVA11F6M",
	"zIGgYKx1rlj2YOKdmefNuO+UsWbLOa6qEDAj+LcM9TSNrd2JbmtIdvdPhGTPf/yG1Rqw2tM/ah652Pcb",
	"PtsiPjPUrUFeOzb4ciMWe42EiWBkojSbSMfNZOBrJGzcZx0UelV0pVsZlFQenFdtp7aDsT7Xo5PkucaV",
	"5D+fwfsiMIkaVoVEKsb1Rr2eN+5XR4vmSBpx4L6+8NWrCBx/9z8Vmvwj0RMo8NMfR/z9eck+BytppOFH",
	"QYVFTApF6HcUt07gThTxk0V4SDUrhaVfDw+5NJKa4bZwzu0qDHFbDf3dFs6w5Em1FDv8B6Okb2zvNwJx",
	"MQb+RiFWKETQRCLmyLgVpJmH5LsxiW1XRbiX2hdxyyi3SDX71XHuFvHaNxT7V0Sx31Db8lRdkfFmeTUD",
	"Ab6kqvP1C740qF/tStcH/zPoExpm9U2P8E2P8C/CSv6p6aka5mvEiItUBq9V7sWVkOJrJHwYcSWqq3m8",
	"reoF/gBp11KY8Zvw/xtv9y+Niz7rbBoWGWgDlR2Y4p37PR2IVLeuhSKymIYDSqq8mTIxMojAEIJ1KXq5",
	"h2Y843ZWX8Ln28//PwAA//+EPL0RpAoBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
