package scripts_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCleanupContainment(t *testing.T) {
	root := t.TempDir()
	tree := filepath.Join(root, "tree")
	require.NoError(t, os.Mkdir(tree, 0700))
	outside := filepath.Join(root, "outside")
	require.NoError(t, os.WriteFile(outside, []byte("outside"), 0600))
	require.NoError(t, os.Chmod(outside, os.FileMode(0755)|os.ModeSetuid))
	require.NoError(t, os.Symlink(outside, filepath.Join(tree, "link")))
	before, err := os.Stat(outside)
	require.NoError(t, err)
	command := exec.Command("bash", "-c", `source ../../deploy/scripts/clean_quadlets.sh; podman() { shift; local args=("$@"); for index in "${!args[@]}"; do if [[ "${args[index]}" == 0:0 ]]; then args[index]="$(id -u):$(id -g)"; fi; done; "${args[@]}"; }; reclaim_rootless_tree "$1"`, "test", tree)
	output, err := command.CombinedOutput()
	require.NoError(t, err, string(output))
	after, err := os.Stat(outside)
	require.NoError(t, err)
	require.Equal(t, before.Mode(), after.Mode())
}

func TestGeneratedUnitCleanup(t *testing.T) {
	root := t.TempDir()
	generated := filepath.Join(root, "flightctl-new.container")
	custom := filepath.Join(root, "flightctl-custom.container")
	require.NoError(t, os.WriteFile(generated, []byte("# Generated by Flight Control deployment; test\n"), 0600))
	require.NoError(t, os.WriteFile(custom, []byte("custom"), 0600))
	dropin := filepath.Join(root, "flightctl-new.container.d", "flightctl-generated.conf")
	require.NoError(t, os.MkdirAll(filepath.Dir(dropin), 0700))
	require.NoError(t, os.WriteFile(dropin, []byte("# Generated by Flight Control deployment; test\n"), 0600))
	target := filepath.Join(root, "flightctl.target")
	require.NoError(t, os.WriteFile(target, []byte("# Generated by Flight Control deployment; test\n"), 0600))
	wants := filepath.Join(root, "default.target.wants")
	require.NoError(t, os.MkdirAll(wants, 0700))
	for _, name := range []string{"flightctl.target", "flightctl-missing.target"} {
		require.NoError(t, os.Symlink("../"+name, filepath.Join(wants, name)))
	}
	command := exec.Command("bash", "-c", `source ../../deploy/scripts/clean_quadlets.sh; remove_generated_units "$1"`, "test", root)
	output, err := command.CombinedOutput()
	require.NoError(t, err, string(output))
	require.Empty(t, string(output))
	require.NoFileExists(t, generated)
	require.FileExists(t, custom)
	require.NoFileExists(t, dropin)
	for _, name := range []string{"flightctl.target", "flightctl-missing.target"} {
		_, err := os.Lstat(filepath.Join(wants, name))
		require.True(t, os.IsNotExist(err))
	}
}

func TestRenderedServiceMarkersAndPermissions(t *testing.T) {
	for _, standalone := range []bool{false, true} {
		name := "normal"
		if standalone {
			name = "standalone"
		}
		t.Run("When rendering "+name+" it should mark units and preserve readable permissions", func(t *testing.T) {
			root := t.TempDir()
			source := filepath.Join(root, "podman", "flightctl-test")
			require.NoError(t, os.MkdirAll(source, 0700))
			for _, name := range []string{"flightctl-test.container", "flightctl-test-standalone.container", "flightctl-test.service", "flightctl-test.volume"} {
				require.NoError(t, os.WriteFile(filepath.Join(source, name), []byte("[Unit]\n"), 0600))
			}
			mode := ""
			if standalone {
				mode = "standalone"
			}
			command := exec.Command("bash", "-c", `source ../../deploy/scripts/shared.sh; SHARED_SCRIPT_DIR=sentinel; source ../../deploy/scripts/shared.sh; [[ "$SHARED_SCRIPT_DIR" == sentinel ]]; umask 077; QUADLET_FILES_OUTPUT_DIR="$1/quadlets"; SYSTEMD_UNIT_OUTPUT_DIR="$1/units"; render_service test "$1" "$2"`, "test", root, mode)
			output, err := command.CombinedOutput()
			require.NoError(t, err, string(output))
			paths := []string{"quadlets/flightctl-test.container", "quadlets/flightctl-test.volume"}
			if !standalone {
				paths = append(paths, "units/flightctl-test.service")
			}
			for _, path := range paths {
				file := filepath.Join(root, path)
				data, err := os.ReadFile(file)
				require.NoError(t, err)
				require.Contains(t, string(data), "# Generated by Flight Control deployment;")
				info, err := os.Stat(file)
				require.NoError(t, err)
				require.Equal(t, os.FileMode(0644), info.Mode().Perm())
			}
		})
	}
}

func TestHelmInstallWithoutElevation(t *testing.T) {
	root := t.TempDir()
	scripts := filepath.Join(root, "test/scripts")
	tools := filepath.Join(root, "tools")
	require.NoError(t, os.MkdirAll(scripts, 0700))
	require.NoError(t, os.MkdirAll(tools, 0700))
	source, err := os.ReadFile("install_helm.sh")
	require.NoError(t, err)
	installer := filepath.Join(scripts, "install_helm.sh")
	require.NoError(t, os.WriteFile(installer, source, 0700))
	for name, content := range map[string]string{
		"helm":      "#!/bin/sh\nexit 1\n",
		"sha256sum": "#!/bin/sh\ncat >/dev/null\n",
		"sudo":      "#!/bin/sh\necho unexpected elevation >&2\nexit 99\n",
		"curl":      "#!/bin/sh\ncat > \"$3\" <<'INSTALLER'\n#!/bin/sh\n[ \"$USE_SUDO\" = false ] && [ \"$1\" = --no-sudo ] || exit 99\nprintf '#!/bin/sh\\nexit 0\\n' > \"$HELM_INSTALL_DIR/helm\"\nchmod +x \"$HELM_INSTALL_DIR/helm\"\nINSTALLER\n",
	} {
		require.NoError(t, os.WriteFile(filepath.Join(tools, name), []byte(content), 0700))
	}
	command := exec.Command("bash", installer)
	command.Env = append(os.Environ(), "PATH="+tools+":"+os.Getenv("PATH"))
	output, err := command.CombinedOutput()
	require.NoError(t, err, string(output))
	require.FileExists(t, filepath.Join(root, "bin/helm"))
}

func TestHelmKVMPreflight(t *testing.T) {
	for _, test := range []struct {
		name      string
		onlyDB    bool
		kvmStatus string
	}{
		{"When KVM is missing it should warn and deploy", false, "1"},
		{"When deploying only DB it should skip KVM", true, "1"},
		{"When KVM is present it should enable the device", false, "0"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			tools := filepath.Join(root, "tools")
			require.NoError(t, os.MkdirAll(tools, 0700))
			source, err := os.ReadFile("deploy_with_helm.sh")
			require.NoError(t, err)
			script := filepath.Join(root, "deploy_with_helm.sh")
			require.NoError(t, os.WriteFile(script, source, 0700))
			require.NoError(t, os.WriteFile(filepath.Join(root, "functions"), []byte("get_ext_ip() { echo 192.0.2.1; }; kind_load_image() { :; }\n"), 0600))
			for name, content := range map[string]string{
				"id":      "#!/bin/sh\necho 1000\n",
				"kubectl": "#!/bin/sh\nexit 0\n",
				"podman":  "#!/bin/sh\nif [ \"$1\" = exec ]; then printf '%s\\n' \"$*\" >> \"$PROBE_LOG\"; exit \"$KVM_STATUS\"; fi\nexit 0\n",
				"helm":    "#!/bin/sh\n[ \"$1\" = dependency ] && exit 0\nprintf '%s\\n' \"$@\" > \"$HELM_LOG\"\nexit 42\n",
			} {
				require.NoError(t, os.WriteFile(filepath.Join(tools, name), []byte(content), 0700))
			}
			args := []string{script}
			if test.onlyDB {
				args = append(args, "--only-db")
			}
			command := exec.Command("bash", args...)
			command.Env = []string{"PATH=" + tools + ":" + os.Getenv("PATH"), "HOME=" + root, "KIND_CLUSTER_NAME=review", "KVM_STATUS=" + test.kvmStatus, "PROBE_LOG=" + filepath.Join(root, "probe"), "HELM_LOG=" + filepath.Join(root, "helm")}
			output, err := command.CombinedOutput()
			var exitError *exec.ExitError
			require.ErrorAs(t, err, &exitError, string(output))
			require.Equal(t, 42, exitError.ExitCode(), string(output))
			if test.onlyDB {
				require.NoFileExists(t, filepath.Join(root, "probe"))
			} else {
				probe, err := os.ReadFile(filepath.Join(root, "probe"))
				require.NoError(t, err)
				require.Contains(t, string(probe), "review-control-plane")
			}
			helmArgs, err := os.ReadFile(filepath.Join(root, "helm"))
			require.NoError(t, err)
			require.Contains(t, string(helmArgs), "kind-review")
			if !test.onlyDB && test.kvmStatus == "0" {
				require.Contains(t, string(helmArgs), "imageBuilderWorker.hostDevices.enabled=false")
			} else {
				require.NotContains(t, string(helmArgs), "imageBuilderWorker.hostDevices.enabled=false")
			}
		})
	}
}

func TestQuadletSudoScopeCase(t *testing.T) {
	for _, value := range []string{"true", "TRUE", "True", "1", "false"} {
		t.Run(value, func(t *testing.T) {
			command := exec.Command("bash", "-c", `IP=192.0.2.1; source ./functions; if quadlet_uses_system_scope; then echo system; else echo user; fi`)
			command.Env = append(os.Environ(), "E2E_SSH_HOST=remote.example", "E2E_SSH_USER=developer", "E2E_USE_SUDO="+value)
			output, err := command.CombinedOutput()
			require.NoError(t, err, string(output))
			want := "system\n"
			if value == "false" {
				want = "user\n"
			}
			require.Equal(t, want, string(output))
		})
	}
}
